// Generated by tools/patchload/gen_table.py from data/modules.json.
// Do not edit by hand.
#include "g2/patch_load.hpp"

#include <array>

namespace g2::patchload {
namespace {

struct Row {
    std::uint8_t type;
    ResourceSpec spec;
};

// {cyclesA, cyclesB, zpMem, unused5, xMemA, yMemA, pMemA, xMemB, yMemB, pMemB, dynRam, qMem, rMem}
constexpr Row kRows[] = {
    {1, {0, 12, 6, 0, 0, 0, 12, 0, 0, 0, 71, 0, 0}}, // Keyboard _kKeyboardModuleSize
    {3, {19, 0, 0, 0, 1, 0, 21, 0, 0, 0, 167, 0, 0}}, // 4-Out _kOut4ModuleSize
    {4, {15, 0, 0, 0, 1, 1, 17, 0, 0, 0, 167, 0, 0}}, // 2-Out _kOut2ModuleSize
    {5, {0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 71, 0, 0}}, // Invert _kInvertModuleSize
    {6, {0, 0, 0, 80, 0, 0, 0, 0, 0, 0, 623, 0, 0}}, // Morph _kMorphModuleSize
    {7, {6, 0, 1, 0, 11, 0, 7, 0, 0, 0, 423, 0, 0}}, // OscB _kOscB2ModuleSize
    {8, {6, 0, 1, 0, 10, 0, 7, 0, 0, 0, 391, 0, 0}}, // OscShpB _kOscC2ModuleSize
    {9, {0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 327, 0, 0}}, // OscC _kOscD2ModuleSize
    {12, {0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 199, 0, 0}}, // Reverb _kFxReverbModuleSize
    {13, {0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 327, 0, 0}}, // OscString _kOscKarplusModuleSize
    {15, {12, 0, 2, 59, 1, 1, 1, 1, 1, 1, 133, 0, 0}}, // Sw8-1 _kSwitch8_1ModuleSize
    {17, {12, 0, 2, 0, 1, 1, 1, 1, 1, 1, 103, 0, 0}}, // ValSw1-2 _kMux1_2ModuleSize
    {18, {0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 167, 0, 0}}, // X-Fade _kMixSModuleSize
    {19, {12, 0, 1, 0, 1, 1, 1, 1, 1, 1, 231, 0, 0}}, // Mix4-1B _kMix4_1aModuleSize
    {20, {5, 31, 2, 0, 0, 0, 0, 0, 0, 0, 327, 0, 0}}, // EnvADSR _kEnvADSRModuleSize
    {21, {12, 0, 8, 0, 1, 1, 1, 1, 1, 1, 71, 0, 0}}, // Mux1-8 _kMux1_8ModuleSize
    {22, {0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 103, 0, 0}}, // PartQuant _kHarmqntModuleSize
    {23, {5, 85, 2, 0, 0, 0, 0, 0, 0, 0, 391, 0, 0}}, // ModADSR _kEnvADSRModModuleSize
    {24, {0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 231, 0, 0}}, // LfoC _kLfoF2ModuleSize
    {25, {0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 455, 0, 0}}, // LfoShpA _kLfoC2ModuleSize
    {26, {3, 0, 1, 0, 6, 0, 4, 0, 0, 0, 327, 0, 0}}, // LfoA _kLfoA2ModuleSize
    {27, {0, 24, 1, 0, 0, 0, 0, 0, 0, 0, 231, 0, 0}}, // OscMaster _kMstoscModuleSize
    {28, {0, 53, 1, 0, 0, 0, 0, 0, 0, 0, 199, 0, 0}}, // Saturate _kSaturateModuleSize
    {29, {0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 231, 0, 0}}, // MetNoise _kMetalNoiseModuleSize
    {30, {17, 0, 7, 0, 0, 0, 16, 0, 0, 0, 71, 0, 0}}, // Device _kDeviceModuleSize
    {31, {13, 0, 1, 0, 0, 0, 0, 0, 0, 0, 135, 0, 0}}, // Noise _kNoiseaModuleSize
    {32, {0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 263, 0, 0}}, // Eq2Band _kFltEqLoHiModuleSize
    {33, {0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 327, 0, 0}}, // Eq3band _kFltEqLoMidHiModuleSize
    {34, {0, 53, 1, 0, 0, 0, 0, 0, 0, 0, 199, 0, 0}}, // ShpExp _kShapeModuleSize
    {36, {12, 0, 2, 10, 1, 1, 1, 1, 1, 1, 108, 0, 0}}, // SwOnOffM _kSwitch1_1ModuleSize
    {38, {0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 167, 0, 0}}, // Pulse _kLogicPulseModuleSize
    {40, {12, 0, 1, 0, 1, 1, 1, 1, 1, 1, 391, 0, 0}}, // Mix8-1B _kMix8_1bModuleSize
    {41, {12, 0, 2, 0, 1, 1, 1, 1, 1, 1, 135, 0, 0}}, // EnvH _kEnvHModuleSize
    {42, {0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 167, 0, 0}}, // Delay _kLogicDelayModuleSize
    {43, {0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 135, 0, 0}}, // Constant _kConstModuleSize
    {44, {0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 71, 0, 0}}, // LevMult _kVcaModuleSize
    {45, {0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 391, 3, 0}}, // FltVoice _kFormFltModuleSize
    {46, {0, 0, 2, 0, 1, 1, 1, 1, 1, 1, 295, 0, 0}}, // EnvAHD _kEnvAHDModuleSize
    {47, {0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 167, 0, 0}}, // Pan _kPanModuleSize
    {48, {0, 0, 2, 0, 1, 1, 1, 1, 1, 1, 487, 0, 0}}, // MixStereo _kStMixerModuleSize
    {49, {34, 32, 3, 0, 4, 2, 35, 4, 4, 33, 295, 0, 0}}, // FltMulti _kFilterAModuleSize
    {50, {12, 0, 1, 10, 1, 1, 1, 1, 1, 1, 172, 0, 0}}, // ConstSwT _kSwitchOffsetModuleSize
    {51, {60, 0, 1, 0, 7, 10, 61, 0, 0, 0, 391, 0, 0}}, // FltNord _kFilterCModuleSize
    {52, {4, 45, 2, 0, 0, 0, 0, 0, 0, 0, 487, 0, 0}}, // EnvMulti _kEnvMultiModuleSize
    {53, {12, 0, 1, 0, 1, 1, 1, 1, 1, 1, 71, 0, 0}}, // S&H _kSampleHoldModuleSize
    {54, {0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 231, 0, 0}}, // FltStatic _kFltStaticModuleSize
    {55, {12, 0, 2, 0, 1, 1, 1, 1, 1, 1, 135, 0, 0}}, // EnvD _kEnvDcyModuleSize
    {57, {0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 200, 0, 0}}, // Automate _kMIDIAutomateModuleSize
    {58, {71, 100, 1, 0, 0, 0, 0, 0, 0, 0, 583, 0, 0}}, // DrumSynth _kDrumModuleSize
    {59, {0, 5, 1, 0, 0, 0, 0, 0, 0, 0, 103, 0, 0}}, // CompLev _kCompareModuleSize
    {60, {15, 52, 1, 0, 1, 1, 1, 1, 1, 1, 103, 0, 0}}, // Mux8-1X _kXMux8_1ModuleSize
    {61, {0, 15, 1, 0, 0, 0, 0, 1, 2, 16, 199, 0, 0}}, // Clip _kDistaModuleSize
    {62, {25, 25, 1, 0, 0, 0, 0, 0, 0, 0, 231, 0, 0}}, // Overdrive _kDistbModuleSize
    {63, {1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 199, 0, 0}}, // Scratch _kPitchShuttleModuleSize
    {64, {0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 71, 0, 0}}, // Gate _kGateModuleSize
    {66, {12, 0, 1, 0, 1, 1, 1, 1, 1, 1, 231, 0, 0}}, // Mix2-1B _kMix2_1ModuleSize
    {68, {0, 0, 4, 0, 1, 1, 1, 1, 1, 1, 231, 0, 0}}, // ClkGen _kClkGenModuleSize
    {69, {0, 19, 1, 0, 0, 0, 0, 0, 0, 0, 103, 0, 0}}, // ClkDiv _kClkdivModuleSize
    {71, {18, 0, 1, 0, 3, 2, 18, 0, 0, 0, 135, 0, 0}}, // EnvFollow _kEnvFol2ModuleSize
    {72, {0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 103, 0, 0}}, // NoteScaler _kScale3ModuleSize
    {74, {0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 167, 0, 0}}, // WaveWrap _kWraperModuleSize
    {75, {0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 135, 0, 0}}, // NoteQuant _kNoteqModuleSize
    {76, {12, 0, 2, 10, 1, 1, 1, 1, 1, 1, 108, 0, 0}}, // SwOnOffT _kOnOffModuleSize
    {78, {12, 0, 9, 59, 1, 1, 1, 1, 1, 1, 133, 0, 0}}, // Sw1-8 _kSwitch1_8ModuleSize
    {79, {12, 0, 2, 31, 1, 1, 1, 1, 1, 1, 119, 0, 0}}, // Sw4-1 _kSwitch4_1ModuleSize
    {81, {0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 135, 0, 0}}, // LevAmp _kAmpModuleSize
    {82, {0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 135, 0, 0}}, // Rect _kDiodModuleSize
    {83, {0, 18, 1, 0, 0, 0, 0, 3, 1, 19, 135, 0, 0}}, // ShpStatic _kVeldynModuleSize
    {84, {5, 25, 3, 0, 0, 0, 0, 0, 0, 0, 327, 0, 0}}, // EnvADR _kEnvADModuleSize
    {85, {12, 0, 2, 0, 1, 1, 1, 1, 1, 1, 135, 0, 0}}, // WindSw _kSwitchWinModuleSize
    {86, {12, 0, 8, 0, 1, 1, 1, 1, 1, 1, 71, 0, 0}}, // 8Counter _kCounter8ModuleSize
    {87, {12, 0, 1, 0, 1, 1, 1, 1, 1, 1, 199, 0, 0}}, // FltLP _kFilterLPModuleSize
    {88, {12, 0, 5, 31, 1, 1, 1, 1, 1, 1, 119, 0, 0}}, // Sw1-4 _kSwitch1_4ModuleSize
    {89, {59, 0, 1, 0, 521, 142, 60, 0, 0, 0, 199, 0, 0}}, // Flanger _kFlangerModuleSize
    {90, {12, 0, 3, 17, 1, 1, 1, 1, 1, 1, 112, 0, 0}}, // Sw1-2 _kSwitch1_2ModuleSize
    {91, {0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 71, 0, 0}}, // FlipFlop _kFlipFlopModuleSize
    {92, {34, 40, 1, 0, 6, 4, 34, 4, 4, 41, 263, 0, 0}}, // FltClassic _kFilterHModuleSize
    {94, {0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 167, 1, 0}}, // StChorus _kUnisonModuleSize
    {95, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 135, 0, 0}}, // Gain _kToolbarModuleSize
    {96, {2, 0, 1, 0, 4, 0, 3, 0, 0, 0, 231, 0, 0}}, // OscD _kOscF2ModuleSize
    {97, {3, 0, 1, 0, 6, 0, 4, 0, 0, 0, 295, 0, 0}}, // OscA _kOscA2ModuleSize
    {98, {129, 0, 2, 0, 19, 22, 130, 0, 0, 0, 199, 0, 0}}, // FreqShift _kBodeModuleSize
    {100, {12, 0, 2, 17, 1, 1, 1, 1, 1, 1, 112, 0, 0}}, // Sw2-1 _kSwitch2_1ModuleSize
    {102, {0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 423, 0, 0}}, // FltPhase _kAllpassModuleSize
    {103, {23, 13, 1, 0, 3, 4, 24, 2, 4, 14, 231, 0, 0}}, // EqPeak _kEqPeakModuleSize
    {105, {12, 0, 1, 0, 1, 1, 1, 1, 1, 1, 103, 0, 0}}, // ValSw2-1 _kMux2_1ModuleSize
    {106, {0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 327, 0, 0}}, // OscNoise _kTunedNoiseModuleSize
    {108, {96, 1156, 1, 0, 350, 393, 1258, 0, 0, 0, 647, 0, 0}}, // Vocoder _kVocoderModuleSize
    {112, {0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 135, 2, 0}}, // LevAdd _kLvladdModuleSize
    {113, {0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 135, 0, 0}}, // Fade1-2 _kFade1t2ModuleSize
    {114, {0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 135, 0, 0}}, // Fade2-1 _kFade2t1ModuleSize
    {115, {0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 199, 0, 0}}, // LevScaler _kAmpProcModuleSize
    {116, {12, 0, 1, 0, 1, 1, 1, 1, 1, 1, 103, 0, 0}}, // Mix8-1A _kMix8_1aModuleSize
    {117, {0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 135, 0, 0}}, // LevMod _kAmModuleSize
    {118, {27, 0, 1, 0, 0, 0, 0, 0, 0, 0, 199, 0, 0}}, // Digitizer _kResampModuleSize
    {119, {0, 0, 2, 0, 1, 1, 1, 1, 1, 1, 423, 0, 0}}, // EnvADDSR _kEnvADBDSRModuleSize
    {121, {0, 0, 3, 6, 1, 1, 1, 1, 1, 1, 1258, 0, 0}}, // SeqNote _kSeqNoteModuleSize
    {123, {12, 0, 1, 40, 1, 1, 1, 1, 1, 1, 411, 0, 0}}, // Mix4-1C _kMix4_1bModuleSize
    {124, {12, 0, 1, 0, 1, 1, 1, 1, 1, 1, 71, 0, 0}}, // Mux8-1 _kMux8_1ModuleSize
    {125, {0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 167, 0, 0}}, // WahWah _kWahModuleSize
    {126, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 71, 0, 0}}, // Name _kNameModuleSize
    {127, {21, 0, 2, 0, 0, 0, 0, 0, 0, 0, 167, 0, 0}}, // Fx-In _kPolyinModuleSize
    {128, {0, 7, 2, 0, 0, 0, 0, 0, 0, 8, 71, 0, 0}}, // MinMax _kMinMaxModuleSize
    {130, {12, 0, 8, 0, 1, 1, 1, 1, 1, 1, 71, 0, 0}}, // BinCounter _kCounterBinModuleSize
    {131, {12, 0, 8, 0, 0, 0, 0, 0, 0, 0, 71, 0, 0}}, // ADConv _kADConvModuleSize
    {132, {12, 0, 1, 0, 0, 0, 0, 0, 0, 0, 71, 0, 0}}, // DAConv _kDAConvModuleSize
    {134, {0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 199, 0, 0}}, // FltHP _kFilterHPModuleSize
    {135, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 135, 0, 0}}, // Glide _kTBGlideModuleSize
    {136, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 199, 0, 0}}, // Arpeggiator _kTBArpeggiatorModuleSize
    {137, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 135, 0, 0}}, // Bend _kTBBendModuleSize
    {138, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 167, 0, 0}}, // Vibrato _kTBVibratoModuleSize
    {139, {12, 0, 1, 0, 1, 1, 1, 1, 1, 1, 71, 0, 0}}, // T&H _kTrackHoldModuleSize
    {140, {12, 0, 2, 40, 1, 1, 1, 1, 1, 1, 379, 0, 0}}, // Mix4-1S _kMix4_2ModuleSize
    {141, {0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 167, 0, 0}}, // CtrlSend _kMIDICtrlSendModuleSize
    {142, {0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 135, 0, 0}}, // PCSend _kMIDIPCSendModuleSize
    {143, {0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 167, 0, 0}}, // NoteSend _kMIDINoteSendModuleSize
    {144, {0, 0, 3, 0, 1, 1, 1, 1, 1, 1, 1223, 0, 0}}, // SeqEvent _kSeqEventModuleSize
    {145, {0, 0, 3, 0, 1, 1, 1, 1, 1, 1, 1287, 0, 0}}, // SeqVal _kSeqValueModuleSize
    {146, {0, 0, 3, 0, 1, 1, 1, 1, 1, 1, 1287, 0, 0}}, // SeqLev _kSeqCtrlModuleSize
    {147, {0, 0, 2, 0, 1, 1, 1, 1, 1, 1, 135, 0, 0}}, // CtrlRcv _kMIDICtrlRcvModuleSize
    {148, {0, 0, 3, 0, 1, 1, 1, 1, 1, 1, 135, 0, 0}}, // NoteRcv _kMIDINoteRcvModuleSize
    {149, {0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 263, 0, 0}}, // NoteZone _kMIDINoteZoneModuleSize
    {150, {0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 295, 0, 0}}, // Compress _kCompressorModuleSize
    {152, {0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 519, 0, 0}}, // KeyQuant _kKeyQuantizerModuleSize
    {153, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 135, 0, 0}}, // Misc _kTBMiscModuleSize
    {154, {0, 0, 2, 0, 1, 1, 1, 1, 1, 1, 1255, 0, 0}}, // SeqCtr _kSeqVoltModuleSize
    {156, {0, 0, 3, 0, 1, 1, 1, 1, 1, 1, 103, 0, 0}}, // NoteDet _kNoteDetectorModuleSize
    {157, {0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 135, 0, 0}}, // LevConv _kLevelConverterModuleSize
    {158, {0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 167, 0, 0}}, // Glide _kPortamentoModuleSize
    {159, {0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 71, 0, 0}}, // CompSig _kCompareBModuleSize
    {160, {0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 71, 0, 0}}, // ZeroCnt _kPitchTrackModuleSize
    {161, {12, 0, 1, 80, 1, 1, 1, 1, 1, 1, 687, 0, 0}}, // MixFader _kMix8_1FaderModuleSize
    {162, {0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 327, 0, 0}}, // FltComb _kDelayLineModuleSize
    {163, {6, 0, 1, 0, 11, 0, 7, 0, 0, 0, 423, 0, 0}}, // OscShpA _kOscSinShpModuleSize
    {164, {6, 0, 1, 0, 11, 0, 7, 0, 0, 0, 519, 0, 0}}, // OscDual _kOscJunModuleSize
    {165, {15, 52, 7, 0, 1, 1, 1, 1, 1, 1, 135, 0, 0}}, // DXRouter _kDXRouterModuleSize
    {167, {1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 231, 0, 0}}, // PShift _kPitchShifterModuleSize
    {169, {0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 327, 0, 0}}, // ModAHD _kEnvAHDModModuleSize
    {170, {15, 0, 2, 0, 0, 0, 0, 0, 0, 0, 167, 0, 0}}, // 2-In _kIn2ModuleSize
    {171, {15, 0, 4, 0, 0, 0, 0, 0, 0, 0, 167, 0, 0}}, // 4-In _kIn4ModuleSize
    {172, {0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 103, 0, 0}}, // DlySingleA _kDly1aModuleSize
    {173, {0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 135, 0, 0}}, // DlySingleB _kDly1bModuleSize
    {174, {0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 199, 0, 0}}, // DelayDual _kDly2ModuleSize
    {175, {0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 359, 0, 0}}, // DelayQuad _kDly4ModuleSize
    {176, {0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 263, 0, 0}}, // DelayA _kDlyAModuleSize
    {177, {0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 359, 0, 0}}, // DelayB _kDlyBModuleSize
    {178, {0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 103, 0, 0}}, // DlyClock _kDlyClockModuleSize
    {179, {0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 71, 0, 0}}, // DlyShiftReg _kDlyShiftModuleSize
    {180, {0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 871, 0, 0}}, // Operator _kOperatorModuleSize
    {181, {0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 103, 0, 0}}, // DlyEight _kDly8ModuleSize
    {182, {0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 423, 0, 0}}, // DlyStereo _kDlyStereoModuleSize
    {183, {0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 295, 0, 0}}, // OscPM _kOscPHModuleSize
    {184, {12, 0, 1, 10, 1, 1, 1, 1, 1, 1, 172, 0, 0}}, // Mix1-1A _kMix1_1ModuleSize
    {185, {12, 0, 2, 10, 1, 1, 1, 1, 1, 1, 172, 0, 0}}, // Mix1-1S _kMix2_2ModuleSize
    {186, {12, 0, 3, 10, 1, 1, 1, 1, 1, 1, 108, 0, 0}}, // Sw1-2M _kSwitch1_2MomModuleSize
    {187, {12, 0, 2, 10, 1, 1, 1, 1, 1, 1, 108, 0, 0}}, // Sw2-1M _kSwitch2_1MomModuleSize
    {188, {12, 0, 1, 10, 1, 1, 1, 1, 1, 1, 172, 0, 0}}, // ConstSwM _kSwitchOffsetMomModuleSize
    {189, {0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 199, 0, 0}}, // NoiseGate _kNoiseGateModuleSize
    {190, {0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 391, 0, 0}}, // LfoB _kLfoB2ModuleSize
    {192, {0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 199, 0, 0}}, // Phaser _kPhaserModuleSize
    {193, {0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 71, 0, 0}}, // Mix4-1A _kMix4_1cModuleSize
    {194, {12, 0, 1, 20, 1, 1, 1, 1, 1, 1, 241, 0, 0}}, // Mix2-1A _kMix2_1aModuleSize
    {195, {0, 0, 1, 10, 1, 1, 1, 1, 1, 1, 204, 0, 0}}, // ModAmt _kModAmountModuleSize
    {196, {33, 21, 1, 0, 0, 0, 0, 0, 0, 0, 359, 0, 0}}, // OscPerc _kOscPercModuleSize
    {197, {17, 0, 3, 0, 0, 0, 16, 0, 0, 0, 71, 0, 0}}, // Status _kStatusModuleSize
    {198, {12, 0, 3, 0, 1, 1, 1, 1, 1, 1, 103, 0, 0}}, // PitchTrack _kPitchDetectModuleSize
    {199, {17, 0, 3, 0, 0, 0, 16, 0, 0, 0, 103, 0, 0}}, // MonoKey _kMonoKeyboardModuleSize
    {200, {0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 295, 0, 0}}, // RandomA _kRndLfoAModuleSize
    {202, {3, 0, 1, 0, 6, 0, 4, 0, 0, 0, 359, 0, 0}}, // RandomB _kRndLfoBModuleSize
    {204, {0, 0, 1, 10, 0, 0, 0, 0, 0, 0, 236, 0, 0}}, // RndClkA _kRndClkAModuleSize
    {205, {0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 199, 0, 0}}, // RndTrig _kRndClkBModuleSize
    {206, {0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 231, 0, 0}}, // RndClkB _kRndClkCModuleSize
    {208, {0, 73, 1, 0, 0, 0, 0, 0, 0, 0, 295, 0, 0}}, // RndPattern _kRndClkPatternModuleSize
};

constexpr std::array<const ResourceSpec*, 256> makeIndex()
{
    std::array<const ResourceSpec*, 256> index{};
    for (const Row& r : kRows)
        index[r.type] = &r.spec;
    return index;
}

constexpr std::array<const ResourceSpec*, 256> kIndex = makeIndex();

} // namespace

const ResourceSpec* moduleSpec(std::uint8_t type)
{
    return kIndex[type];
}

} // namespace g2::patchload
