// Generated by tools/moduledb/gen_replace.py from tools/moduledb/replace_facts.json
// and data/modules.json. Do not edit by hand.
#include "g2/replace.hpp"

#include <iterator>

namespace g2::replace {
namespace {

// Shaper Group (CReplaceDataBase::Module_Begin @ 0010ae8c)
const Member kMembers0[] = {
    {61, 7}, // Clip
    {62, 7}, // Overdrive
    {28, 7}, // Saturate
    {34, 7}, // ShpExp
    {74, 7}, // WaveWrap
    {83, 7}, // ShpStatic
    {82, 7}, // Rect
};
const InputItem kInputs0_0[] = { // Inputs
    {61, 0, 255, 255},
    {62, 0, 255, 255},
    {28, 0, 255, 255},
    {34, 0, 255, 255},
    {74, 0, 255, 255},
    {83, 0, 255, 255},
    {82, 0, 255, 255},
};
const InputItem kInputs0_1[] = { // Inputs Mod
    {61, 1, 0, 255},
    {62, 1, 0, 255},
    {28, 1, 1, 255},
    {34, 1, 1, 255},
    {74, 1, 0, 255},
};
const ItemGroup<InputItem> kInputs0[] = {
    {"Inputs", kInputs0_0},
    {"Inputs Mod", kInputs0_1},
};
const OutputItem kOutputs0_0[] = { // Outputs
    {61, 0},
    {74, 0},
    {82, 0},
    {62, 0},
    {28, 0},
    {34, 0},
    {83, 0},
};
const ItemGroup<OutputItem> kOutputs0[] = {
    {"Outputs", kOutputs0_0},
};
const ParamItem kParams0_0[] = { // Params
    {61, 1},
    {74, 1},
    {62, 1},
    {28, 0},
    {34, 0},
};
const ParamItem kParams0_1[] = { // Bypass
    {61, 3},
    {74, 2},
    {82, 1},
    {62, 2},
    {28, 2},
    {34, 2},
    {83, 1},
};
const ItemGroup<ParamItem> kParams0[] = {
    {"Params", kParams0_0},
    {"Bypass", kParams0_1},
};

// Level Group (CReplaceDataBase::Module_Begin @ 0010b401)
const Member kMembers1[] = {
    {43, 7}, // Constant
    {188, 7}, // ConstSwM
    {50, 7}, // ConstSwT
    {112, 7}, // LevAdd
    {157, 7}, // LevConv
    {81, 7}, // LevAmp
    {44, 7}, // LevMult
    {117, 7}, // LevMod
    {71, 7}, // EnvFollow
    {189, 7}, // NoiseGate
    {59, 7}, // CompLev
    {159, 7}, // CompSig
    {128, 7}, // MinMax
    {195, 7}, // ModAmt
};
const InputItem kInputs1_0[] = { // Inputs
    {112, 0, 255, 255},
    {157, 0, 255, 255},
    {81, 0, 255, 255},
    {44, 0, 255, 255},
    {117, 0, 255, 255},
    {71, 0, 255, 255},
    {189, 0, 255, 255},
    {59, 0, 255, 255},
    {159, 0, 255, 255},
    {128, 0, 255, 255},
    {195, 0, 255, 255},
};
const InputItem kInputs1_1[] = { // Inputs B
    {159, 1, 255, 255},
    {128, 1, 255, 255},
};
const InputItem kInputs1_2[] = { // Inputs Mod
    {44, 1, 255, 255},
    {117, 1, 0, 255},
    {195, 1, 0, 255},
};
const ItemGroup<InputItem> kInputs1[] = {
    {"Inputs", kInputs1_0},
    {"Inputs B", kInputs1_1},
    {"Inputs Mod", kInputs1_2},
};
const OutputItem kOutputs1_0[] = { // Outputs
    {43, 0},
    {188, 0},
    {50, 0},
    {112, 0},
    {157, 0},
    {81, 0},
    {44, 0},
    {117, 0},
    {71, 0},
    {189, 0},
    {59, 0},
    {159, 0},
    {128, 0},
    {195, 0},
};
const ItemGroup<OutputItem> kOutputs1[] = {
    {"Outputs", kOutputs1_0},
};
const ParamItem kParams1_0[] = { // Params
    {43, 0},
    {50, 0},
    {112, 0},
    {81, 0},
    {117, 1},
    {59, 0},
    {195, 0},
};
const ParamItem kParams1_1[] = { // Params Range
    {43, 1},
    {188, 2},
    {50, 2},
    {112, 1},
    {157, 1},
    {81, 1},
};
const ParamItem kParams1_2[] = { // Params Atk
    {71, 0},
    {189, 1},
};
const ParamItem kParams1_3[] = { // Params Dcy
    {71, 1},
    {189, 2},
};
const ItemGroup<ParamItem> kParams1[] = {
    {"Params", kParams1_0},
    {"Params Range", kParams1_1},
    {"Params Atk", kParams1_2},
    {"Params Dcy", kParams1_3},
};

// MIDI Group Send (CReplaceDataBase::Module_Begin @ 0010bc63)
const Member kMembers2[] = {
    {141, 7}, // CtrlSend
    {142, 7}, // PCSend
    {143, 7}, // NoteSend
    {57, 7}, // Automate
};
const InputItem kInputs2_0[] = { // Inputs
    {141, 0, 255, 255},
    {142, 0, 255, 255},
    {143, 0, 255, 255},
    {57, 0, 255, 255},
};
const InputItem kInputs2_1[] = { // Inputs Ctrl
    {141, 1, 255, 255},
    {142, 1, 255, 255},
    {143, 2, 255, 255},
};
const ItemGroup<InputItem> kInputs2[] = {
    {"Inputs", kInputs2_0},
    {"Inputs Ctrl", kInputs2_1},
};
const OutputItem kOutputs2_0[] = { // Outputs
    {141, 0},
    {142, 0},
    {57, 0},
};
const ItemGroup<OutputItem> kOutputs2[] = {
    {"Outputs", kOutputs2_0},
};
const ParamItem kParams2_0[] = { // Params Chan
    {141, 2},
    {142, 1},
    {143, 2},
    {57, 2},
};
const ParamItem kParams2_1[] = { // Params Ctrl
    {141, 0},
    {142, 0},
    {143, 1},
    {57, 0},
};
const ParamItem kParams2_2[] = { // Params Value
    {141, 1},
    {143, 0},
    {57, 1},
};
const ItemGroup<ParamItem> kParams2[] = {
    {"Params Chan", kParams2_0},
    {"Params Ctrl", kParams2_1},
    {"Params Value", kParams2_2},
};

// MIDI Group Recv (CReplaceDataBase::Module_Begin @ 0010c029)
const Member kMembers3[] = {
    {147, 7}, // CtrlRcv
    {148, 7}, // NoteRcv
};
const OutputItem kOutputs3_0[] = { // Outputs
    {147, 0},
    {148, 0},
};
const OutputItem kOutputs3_1[] = { // Outputs Ctrl
    {147, 1},
    {148, 1},
};
const ItemGroup<OutputItem> kOutputs3[] = {
    {"Outputs", kOutputs3_0},
    {"Outputs Ctrl", kOutputs3_1},
};
const ParamItem kParams3_0[] = { // Params Chan
    {147, 1},
    {148, 1},
};
const ParamItem kParams3_1[] = { // Params Ctrl
    {147, 0},
    {148, 0},
};
const ItemGroup<ParamItem> kParams3[] = {
    {"Params Chan", kParams3_0},
    {"Params Ctrl", kParams3_1},
};

// Note Group (CReplaceDataBase::Module_Begin @ 0010c1a7)
const Member kMembers4[] = {
    {75, 7}, // NoteQuant
    {152, 7}, // KeyQuant
    {22, 7}, // PartQuant
    {72, 7}, // NoteScaler
    {158, 7}, // Glide
    {160, 7}, // ZeroCnt
    {198, 7}, // PitchTrack
};
const InputItem kInputs4_0[] = { // In
    {75, 0, 255, 255},
    {152, 0, 255, 255},
    {22, 0, 255, 255},
    {72, 0, 255, 255},
    {158, 0, 255, 255},
    {160, 0, 255, 255},
    {198, 0, 255, 255},
};
const ItemGroup<InputItem> kInputs4[] = {
    {"In", kInputs4_0},
};
const OutputItem kOutputs4_0[] = { // Out
    {75, 0},
    {152, 0},
    {22, 0},
    {72, 0},
    {158, 0},
    {160, 0},
    {198, 1},
};
const ItemGroup<OutputItem> kOutputs4[] = {
    {"Out", kOutputs4_0},
};
const ParamItem kParams4_0[] = { // Range
    {75, 0},
    {152, 0},
    {22, 0},
    {72, 0},
};
const ItemGroup<ParamItem> kParams4[] = {
    {"Range", kParams4_0},
};

// Osc Group (CReplaceDataBase::Module_Begin @ 0010c528)
const Member kMembers5[] = {
    {97, 7}, // OscA
    {7, 7}, // OscB
    {9, 7}, // OscC
    {96, 7}, // OscD
    {183, 7}, // OscPM
    {163, 7}, // OscShpA
    {8, 7}, // OscShpB
    {164, 7}, // OscDual
    {106, 7}, // OscNoise
    {31, 7}, // Noise
    {29, 7}, // MetNoise
    {196, 7}, // OscPerc
    {58, 7}, // DrumSynth
    {13, 7}, // OscString
    {180, 7}, // Operator
    {27, 7}, // OscMaster
};
const InputItem kInputs5_0[] = { // Sync
    {7, 2, 255, 255},
    {9, 1, 255, 255},
    {183, 1, 255, 255},
    {163, 2, 255, 255},
    {8, 2, 255, 255},
    {164, 2, 255, 255},
};
const InputItem kInputs5_1[] = { // Pitch Fixed
    {97, 0, 255, 255},
    {7, 0, 255, 255},
    {9, 3, 255, 255},
    {96, 0, 255, 255},
    {183, 3, 255, 255},
    {163, 0, 255, 255},
    {8, 0, 255, 255},
    {164, 0, 255, 255},
    {13, 1, 255, 255},
    {196, 0, 255, 255},
    {58, 2, 255, 255},
    {106, 0, 255, 255},
    {27, 0, 255, 255},
};
const InputItem kInputs5_2[] = { // Pitch Variable
    {97, 1, 3, 255},
    {7, 1, 3, 255},
    {9, 0, 7, 255},
    {183, 0, 6, 255},
    {163, 1, 3, 255},
    {8, 1, 3, 255},
    {164, 1, 3, 255},
    {13, 2, 3, 255},
    {196, 1, 4, 255},
    {106, 1, 3, 255},
    {27, 1, 4, 255},
};
const InputItem kInputs5_3[] = { // PW & Shape
    {7, 4, 7, 255},
    {163, 4, 8, 255},
    {8, 4, 7, 255},
    {164, 3, 6, 255},
};
const InputItem kInputs5_4[] = { // FM & Phase
    {7, 3, 5, 255},
    {9, 2, 4, 255},
    {183, 2, 4, 255},
    {163, 3, 5, 255},
    {8, 3, 5, 255},
    {164, 4, 12, 255},
};
const InputItem kInputs5_5[] = { // Trig
    {196, 2, 255, 255},
    {58, 0, 255, 255},
};
const ItemGroup<InputItem> kInputs5[] = {
    {"Sync", kInputs5_0},
    {"Pitch Fixed", kInputs5_1},
    {"Pitch Variable", kInputs5_2},
    {"PW & Shape", kInputs5_3},
    {"FM & Phase", kInputs5_4},
    {"Trig", kInputs5_5},
};
const OutputItem kOutputs5_0[] = { // Main
    {97, 0},
    {7, 0},
    {9, 0},
    {96, 0},
    {183, 0},
    {163, 0},
    {8, 0},
    {164, 0},
    {31, 0},
    {13, 0},
    {196, 0},
    {58, 0},
    {29, 0},
    {106, 0},
    {180, 0},
};
const ItemGroup<OutputItem> kOutputs5[] = {
    {"Main", kOutputs5_0},
};
const ParamItem kParams5_0[] = { // Coarse
    {97, 0},
    {7, 0},
    {9, 0},
    {96, 0},
    {183, 0},
    {163, 0},
    {8, 0},
    {164, 0},
    {13, 0},
    {196, 0},
    {106, 0},
    {27, 0},
};
const ParamItem kParams5_1[] = { // TuneMode
    {97, 6},
    {7, 4},
    {9, 3},
    {96, 3},
    {183, 3},
    {163, 4},
    {8, 4},
    {164, 4},
    {13, 4},
    {196, 2},
    {106, 4},
};
const ParamItem kParams5_2[] = { // Fine
    {97, 1},
    {7, 1},
    {9, 1},
    {96, 1},
    {183, 1},
    {163, 1},
    {8, 1},
    {164, 1},
    {13, 1},
    {196, 1},
    {106, 1},
    {27, 1},
};
const ParamItem kParams5_3[] = { // Wave
    {97, 4},
    {7, 8},
    {163, 9},
};
const ParamItem kParams5_4[] = { // FM Type
    {7, 10},
    {163, 6},
    {8, 9},
};
const ParamItem kParams5_5[] = { // KBT
    {97, 2},
    {7, 2},
    {9, 2},
    {96, 2},
    {183, 2},
    {163, 2},
    {8, 2},
    {164, 2},
    {13, 2},
    {196, 3},
    {106, 2},
    {27, 2},
};
const ParamItem kParams5_6[] = { // PW & Shape
    {7, 6},
    {163, 7},
    {8, 6},
    {164, 11},
    {31, 0},
};
const ParamItem kParams5_7[] = { // Mute
    {97, 5},
    {7, 9},
    {9, 5},
    {96, 4},
    {183, 5},
    {163, 10},
    {8, 8},
    {164, 10},
    {31, 1},
    {13, 7},
    {196, 8},
    {106, 7},
    {29, 2},
};
const ItemGroup<ParamItem> kParams5[] = {
    {"Coarse", kParams5_0},
    {"TuneMode", kParams5_1},
    {"Fine", kParams5_2},
    {"Wave", kParams5_3},
    {"FM Type", kParams5_4},
    {"KBT", kParams5_5},
    {"PW & Shape", kParams5_6},
    {"Mute", kParams5_7},
};

// Keyboard Group (CReplaceDataBase::Module_Begin @ 0010d9dc)
const Member kMembers6[] = {
    {1, 7}, // Keyboard
    {199, 7}, // MonoKey
};
const OutputItem kOutputs6_0[] = { // Pitch
    {1, 0},
    {199, 0},
};
const OutputItem kOutputs6_1[] = { // Gate
    {1, 1},
    {199, 1},
};
const OutputItem kOutputs6_2[] = { // Vel
    {1, 2},
    {199, 2},
};
const ItemGroup<OutputItem> kOutputs6[] = {
    {"Pitch", kOutputs6_0},
    {"Gate", kOutputs6_1},
    {"Vel", kOutputs6_2},
};

// Input Group (CReplaceDataBase::Module_Begin @ 0010db0a)
const Member kMembers7[] = {
    {170, 7}, // 2-In
    {171, 7}, // 4-In
    {127, 1}, // Fx-In
};
const OutputItem kOutputs7_0[] = { // Main
    {170, 0},
    {170, 1},
    {171, 0},
    {171, 1},
    {171, 2},
    {171, 3},
    {127, 0},
    {127, 1},
};
const ItemGroup<OutputItem> kOutputs7[] = {
    {"Main", kOutputs7_0},
};
const ParamItem kParams7_0[] = { // Mute
    {170, 1},
    {171, 1},
    {127, 1},
};
const ParamItem kParams7_1[] = { // Pad
    {170, 2},
    {171, 2},
    {127, 2},
};
const ItemGroup<ParamItem> kParams7[] = {
    {"Mute", kParams7_0},
    {"Pad", kParams7_1},
};

// Output Group (CReplaceDataBase::Module_Begin @ 0010dd4b)
const Member kMembers8[] = {
    {4, 7}, // 2-Out
    {3, 7}, // 4-Out
};
const InputItem kInputs8_0[] = { // Inputs
    {4, 0, 255, 255},
    {4, 1, 255, 255},
    {3, 0, 255, 255},
    {3, 1, 255, 255},
    {3, 2, 255, 255},
    {3, 3, 255, 255},
};
const ItemGroup<InputItem> kInputs8[] = {
    {"Inputs", kInputs8_0},
};
const ParamItem kParams8_0[] = { // Mute
    {4, 1},
    {3, 1},
};
const ParamItem kParams8_1[] = { // Pad
    {4, 2},
    {3, 2},
};
const ItemGroup<ParamItem> kParams8[] = {
    {"Mute", kParams8_0},
    {"Pad", kParams8_1},
};

// Env Group (CReplaceDataBase::Module_Begin @ 0010df4d)
const Member kMembers9[] = {
    {20, 7}, // EnvADSR
    {41, 7}, // EnvH
    {55, 7}, // EnvD
    {84, 7}, // EnvADR
    {46, 7}, // EnvAHD
    {119, 7}, // EnvADDSR
    {52, 7}, // EnvMulti
    {169, 7}, // ModAHD
    {23, 7}, // ModADSR
};
const InputItem kInputs9_0[] = { // Amp Inputs
    {119, 1, 255, 255},
    {52, 2, 255, 255},
    {20, 2, 255, 255},
    {84, 2, 255, 255},
    {55, 1, 255, 255},
    {41, 1, 255, 255},
    {23, 6, 255, 255},
    {169, 5, 255, 255},
    {46, 1, 255, 255},
};
const InputItem kInputs9_1[] = { // VCA Inputs
    {119, 2, 255, 255},
    {52, 1, 255, 255},
    {20, 0, 255, 255},
    {84, 1, 255, 255},
    {55, 2, 255, 255},
    {41, 2, 255, 255},
    {23, 5, 255, 255},
    {169, 4, 255, 255},
    {46, 2, 255, 255},
};
const InputItem kInputs9_2[] = { // Trig & Gate Inputs
    {119, 0, 255, 255},
    {52, 0, 255, 255},
    {20, 1, 255, 255},
    {84, 0, 255, 255},
    {55, 0, 255, 255},
    {41, 0, 255, 255},
    {23, 0, 255, 255},
    {169, 0, 255, 255},
    {46, 0, 255, 255},
};
const InputItem kInputs9_3[] = { // Attack Mod Inputs
    {169, 1, 255, 255},
    {23, 1, 255, 255},
};
const InputItem kInputs9_4[] = { // Decay Mod Inputs
    {169, 3, 255, 255},
    {23, 2, 255, 255},
};
const ItemGroup<InputItem> kInputs9[] = {
    {"Amp Inputs", kInputs9_0},
    {"VCA Inputs", kInputs9_1},
    {"Trig & Gate Inputs", kInputs9_2},
    {"Attack Mod Inputs", kInputs9_3},
    {"Decay Mod Inputs", kInputs9_4},
};
const OutputItem kOutputs9_0[] = { // EnvOut
    {119, 0},
    {52, 0},
    {20, 0},
    {84, 0},
    {55, 0},
    {41, 0},
    {23, 0},
    {169, 0},
    {46, 0},
};
const OutputItem kOutputs9_1[] = { // VCAOut
    {119, 1},
    {52, 1},
    {20, 1},
    {84, 1},
    {55, 1},
    {41, 1},
    {23, 1},
    {169, 1},
    {46, 1},
};
const ItemGroup<OutputItem> kOutputs9[] = {
    {"EnvOut", kOutputs9_0},
    {"VCAOut", kOutputs9_1},
};
const ParamItem kParams9_0[] = { // Attack
    {119, 2},
    {52, 4},
    {20, 1},
    {84, 1},
    {23, 0},
    {46, 1},
    {169, 0},
};
const ParamItem kParams9_1[] = { // Decay
    {119, 3},
    {52, 5},
    {20, 2},
    {84, 3},
    {55, 0},
    {41, 0},
    {23, 1},
    {46, 4},
    {169, 2},
};
const ParamItem kParams9_2[] = { // Sustain
    {119, 6},
    {52, 1},
    {20, 3},
    {23, 2},
};
const ParamItem kParams9_3[] = { // Release
    {119, 7},
    {52, 7},
    {20, 4},
    {23, 3},
};
const ParamItem kParams9_4[] = { // Shape
    {119, 1},
    {52, 12},
    {20, 0},
    {84, 0},
    {46, 0},
};
const ParamItem kParams9_5[] = { // Reset
    {119, 10},
    {52, 8},
    {20, 7},
    {84, 2},
    {46, 3},
};
const ParamItem kParams9_6[] = { // Type
    {119, 9},
    {52, 10},
    {20, 5},
    {84, 5},
    {55, 1},
    {41, 1},
    {23, 8},
    {46, 5},
    {169, 6},
};
const ParamItem kParams9_7[] = { // KBG
    {119, 0},
    {52, 11},
    {20, 6},
    {84, 6},
    {23, 9},
    {46, 6},
    {169, 7},
};
const ParamItem kParams9_8[] = { // AttackModAmount
    {23, 4},
    {169, 3},
};
const ParamItem kParams9_9[] = { // DecayModAmount
    {23, 5},
    {169, 5},
};
const ItemGroup<ParamItem> kParams9[] = {
    {"Attack", kParams9_0},
    {"Decay", kParams9_1},
    {"Sustain", kParams9_2},
    {"Release", kParams9_3},
    {"Shape", kParams9_4},
    {"Reset", kParams9_5},
    {"Type", kParams9_6},
    {"KBG", kParams9_7},
    {"AttackModAmount", kParams9_8},
    {"DecayModAmount", kParams9_9},
};

// Delay Group (CReplaceDataBase::Module_Begin @ 0010efb2)
const Member kMembers10[] = {
    {172, 7}, // DlySingleA
    {173, 7}, // DlySingleB
    {174, 7}, // DelayDual
    {175, 7}, // DelayQuad
    {181, 7}, // DlyEight
    {179, 7}, // DlyShiftReg
    {178, 7}, // DlyClock
    {176, 7}, // DelayA
    {177, 7}, // DelayB
    {182, 7}, // DlyStereo
};
const InputItem kInputs10_0[] = { // Inputs
    {172, 0, 255, 255},
    {173, 0, 255, 255},
    {174, 0, 255, 255},
    {175, 0, 255, 255},
    {181, 0, 255, 255},
    {179, 0, 255, 255},
    {178, 0, 255, 255},
    {176, 0, 255, 255},
    {177, 0, 255, 255},
    {182, 0, 255, 255},
};
const InputItem kInputs10_1[] = { // Delay Time Mod Inputs
    {173, 1, 1, 255},
    {174, 1, 1, 255},
    {174, 2, 3, 255},
    {175, 1, 1, 255},
    {175, 2, 3, 255},
    {175, 3, 5, 255},
    {175, 4, 7, 255},
};
const InputItem kInputs10_2[] = { // ClockInputs
    {179, 1, 255, 255},
    {178, 1, 255, 255},
};
const ItemGroup<InputItem> kInputs10[] = {
    {"Inputs", kInputs10_0},
    {"Delay Time Mod Inputs", kInputs10_1},
    {"ClockInputs", kInputs10_2},
};
const OutputItem kOutputs10_0[] = { // Outputs
    {172, 0},
    {173, 0},
    {174, 0},
    {174, 1},
    {175, 1},
    {175, 2},
    {175, 3},
    {175, 4},
    {181, 0},
    {181, 1},
    {181, 2},
    {181, 3},
    {181, 4},
    {181, 5},
    {181, 6},
    {181, 7},
    {179, 0},
    {179, 1},
    {179, 2},
    {179, 3},
    {179, 4},
    {179, 5},
    {179, 6},
    {179, 7},
    {178, 0},
    {176, 0},
    {177, 0},
    {182, 0},
    {182, 1},
};
const ItemGroup<OutputItem> kOutputs10[] = {
    {"Outputs", kOutputs10_0},
};
const ParamItem kParams10_0[] = { // Time
    {172, 0},
    {173, 0},
    {174, 0},
    {174, 2},
    {175, 0},
    {175, 2},
    {175, 4},
    {175, 6},
    {181, 0},
    {178, 0},
    {176, 0},
    {177, 0},
    {182, 0},
    {182, 1},
};
const ParamItem kParams10_1[] = { // Feedback
    {176, 1},
    {177, 1},
    {182, 2},
    {182, 3},
};
const ParamItem kParams10_2[] = { // Damp
    {176, 2},
    {177, 2},
    {177, 8},
    {182, 7},
};
const ParamItem kParams10_3[] = { // Dry/Wet
    {176, 3},
    {177, 3},
    {182, 8},
};
const ItemGroup<ParamItem> kParams10[] = {
    {"Time", kParams10_0},
    {"Feedback", kParams10_1},
    {"Damp", kParams10_2},
    {"Dry/Wet", kParams10_3},
};

// Switch Group (CReplaceDataBase::Module_Begin @ 0010fb32)
const Member kMembers11[] = {
    {36, 7}, // SwOnOffM
    {76, 7}, // SwOnOffT
    {187, 7}, // Sw2-1M
    {100, 7}, // Sw2-1
    {79, 7}, // Sw4-1
    {15, 7}, // Sw8-1
    {186, 7}, // Sw1-2M
    {90, 7}, // Sw1-2
    {88, 7}, // Sw1-4
    {78, 7}, // Sw1-8
    {105, 7}, // ValSw2-1
    {17, 7}, // ValSw1-2
    {85, 7}, // WindSw
    {124, 7}, // Mux8-1
    {21, 7}, // Mux1-8
    {60, 7}, // Mux8-1X
    {53, 7}, // S&H
    {139, 7}, // T&H
};
const InputItem kInputs11_0[] = { // Inputs Ctrl
    {105, 2, 255, 255},
    {17, 1, 255, 255},
    {85, 1, 255, 255},
    {124, 8, 255, 255},
    {21, 1, 255, 255},
    {60, 8, 255, 255},
    {53, 1, 255, 255},
    {139, 1, 255, 255},
};
const InputItem kInputs11_1[] = { // Inputs
    {36, 0, 255, 255},
    {76, 0, 255, 255},
    {187, 0, 255, 255},
    {187, 1, 255, 255},
    {100, 0, 255, 255},
    {100, 1, 255, 255},
    {79, 0, 255, 255},
    {79, 1, 255, 255},
    {79, 2, 255, 255},
    {79, 3, 255, 255},
    {15, 0, 255, 255},
    {15, 1, 255, 255},
    {15, 2, 255, 255},
    {15, 3, 255, 255},
    {15, 4, 255, 255},
    {15, 5, 255, 255},
    {15, 6, 255, 255},
    {15, 7, 255, 255},
    {186, 0, 255, 255},
    {90, 0, 255, 255},
    {88, 0, 255, 255},
    {78, 0, 255, 255},
    {105, 0, 255, 255},
    {105, 1, 255, 255},
    {17, 0, 255, 255},
    {85, 0, 255, 255},
    {124, 0, 255, 255},
    {124, 1, 255, 255},
    {124, 2, 255, 255},
    {124, 3, 255, 255},
    {124, 4, 255, 255},
    {124, 5, 255, 255},
    {124, 6, 255, 255},
    {124, 7, 255, 255},
    {21, 0, 255, 255},
    {60, 0, 255, 255},
    {60, 1, 255, 255},
    {60, 2, 255, 255},
    {60, 3, 255, 255},
    {60, 4, 255, 255},
    {60, 5, 255, 255},
    {60, 6, 255, 255},
    {60, 7, 255, 255},
    {53, 0, 255, 255},
    {139, 0, 255, 255},
};
const ItemGroup<InputItem> kInputs11[] = {
    {"Inputs Ctrl", kInputs11_0},
    {"Inputs", kInputs11_1},
};
const OutputItem kOutputs11_0[] = { // Outputs Ctrl
    {36, 1},
    {76, 1},
    {187, 1},
    {100, 1},
    {79, 1},
    {15, 1},
    {186, 2},
    {90, 2},
    {88, 4},
    {78, 8},
};
const OutputItem kOutputs11_1[] = { // Outputs
    {36, 0},
    {76, 0},
    {187, 0},
    {100, 0},
    {79, 0},
    {15, 0},
    {186, 1},
    {186, 0},
    {90, 1},
    {90, 0},
    {88, 0},
    {88, 1},
    {88, 2},
    {88, 3},
    {78, 0},
    {78, 1},
    {78, 2},
    {78, 3},
    {78, 4},
    {78, 5},
    {78, 6},
    {78, 7},
    {105, 0},
    {17, 0},
    {17, 1},
    {85, 0},
    {124, 0},
    {21, 0},
    {21, 1},
    {21, 2},
    {21, 3},
    {21, 4},
    {21, 5},
    {21, 6},
    {21, 7},
    {60, 0},
    {53, 0},
    {139, 0},
};
const ItemGroup<OutputItem> kOutputs11[] = {
    {"Outputs Ctrl", kOutputs11_0},
    {"Outputs", kOutputs11_1},
};
const ParamItem kParams11_0[] = { // Select
    {76, 0},
    {100, 0},
    {79, 0},
    {15, 0},
    {90, 0},
    {88, 0},
    {78, 0},
};
const ParamItem kParams11_1[] = { // Ctrl
    {105, 0},
    {17, 0},
    {85, 0},
    {85, 1},
};
const ItemGroup<ParamItem> kParams11[] = {
    {"Select", kParams11_0},
    {"Ctrl", kParams11_1},
};

// Mix Group (CReplaceDataBase::Module_Begin @ 00110de6)
const Member kMembers12[] = {
    {184, 7}, // Mix1-1A
    {185, 7}, // Mix1-1S
    {194, 7}, // Mix2-1A
    {66, 7}, // Mix2-1B
    {193, 7}, // Mix4-1A
    {19, 7}, // Mix4-1B
    {123, 7}, // Mix4-1C
    {140, 7}, // Mix4-1S
    {116, 7}, // Mix8-1A
    {40, 7}, // Mix8-1B
    {161, 7}, // MixFader
    {48, 7}, // MixStereo
    {47, 7}, // Pan
    {18, 7}, // X-Fade
    {113, 7}, // Fade1-2
    {114, 7}, // Fade2-1
};
const InputItem kInputs12_0[] = { // Inputs Chain
    {184, 1, 255, 255},
    {185, 2, 255, 255},
    {185, 3, 255, 255},
    {66, 2, 255, 255},
    {194, 2, 255, 255},
    {19, 4, 255, 255},
    {123, 4, 255, 255},
    {140, 8, 255, 255},
    {140, 9, 255, 255},
    {40, 8, 255, 255},
    {161, 8, 255, 255},
};
const InputItem kInputs12_1[] = { // Inputs
    {184, 0, 0, 1},
    {185, 0, 0, 1},
    {185, 1, 0, 1},
    {66, 0, 1, 255},
    {66, 1, 3, 255},
    {194, 0, 0, 255},
    {194, 1, 2, 255},
    {19, 0, 0, 255},
    {19, 1, 1, 255},
    {19, 2, 2, 255},
    {19, 3, 3, 255},
    {123, 0, 0, 4},
    {123, 1, 1, 5},
    {123, 2, 2, 6},
    {123, 3, 3, 7},
    {193, 0, 255, 255},
    {193, 1, 255, 255},
    {193, 2, 255, 255},
    {193, 3, 255, 255},
    {140, 0, 0, 4},
    {140, 1, 0, 4},
    {140, 2, 1, 5},
    {140, 3, 1, 5},
    {140, 4, 2, 6},
    {140, 5, 2, 6},
    {140, 6, 3, 7},
    {140, 7, 3, 7},
    {116, 0, 255, 255},
    {116, 1, 255, 255},
    {116, 2, 255, 255},
    {116, 3, 255, 255},
    {116, 4, 255, 255},
    {116, 5, 255, 255},
    {116, 6, 255, 255},
    {116, 7, 255, 255},
    {40, 0, 0, 255},
    {40, 1, 1, 255},
    {40, 2, 2, 255},
    {40, 3, 3, 255},
    {40, 4, 4, 255},
    {40, 5, 5, 255},
    {40, 6, 6, 255},
    {40, 7, 7, 255},
    {161, 0, 0, 8},
    {161, 1, 1, 9},
    {161, 2, 2, 10},
    {161, 3, 3, 11},
    {161, 4, 4, 12},
    {161, 5, 5, 13},
    {161, 6, 6, 14},
    {161, 7, 7, 15},
    {48, 0, 0, 255},
    {48, 1, 1, 255},
    {48, 2, 2, 255},
    {48, 3, 3, 255},
    {48, 4, 4, 255},
    {48, 5, 5, 255},
    {47, 0, 255, 255},
    {18, 0, 255, 255},
    {18, 1, 255, 255},
    {113, 0, 255, 255},
    {114, 0, 255, 255},
    {114, 1, 255, 255},
};
const InputItem kInputs12_2[] = { // ModInput
    {47, 1, 255, 255},
    {113, 1, 255, 255},
    {114, 2, 255, 255},
    {18, 2, 255, 255},
};
const ItemGroup<InputItem> kInputs12[] = {
    {"Inputs Chain", kInputs12_0},
    {"Inputs", kInputs12_1},
    {"ModInput", kInputs12_2},
};
const OutputItem kOutputs12_0[] = { // Outputs
    {184, 0},
    {185, 0},
    {185, 1},
    {66, 0},
    {194, 0},
    {19, 0},
    {123, 0},
    {193, 0},
    {140, 0},
    {140, 1},
    {116, 0},
    {40, 0},
    {161, 0},
    {48, 0},
    {48, 1},
    {47, 0},
    {47, 1},
    {18, 0},
    {113, 0},
    {113, 1},
    {114, 0},
};
const ItemGroup<OutputItem> kOutputs12[] = {
    {"Outputs", kOutputs12_0},
};
const ParamItem kParams12_0[] = { // Linear
    {184, 2},
    {185, 2},
    {194, 4},
    {66, 4},
    {19, 4},
    {123, 9},
    {40, 8},
    {161, 16},
    {47, 2},
    {18, 2},
};
const ParamItem kParams12_1[] = { // Padding
    {116, 0},
    {40, 9},
    {161, 17},
};
const ParamItem kParams12_2[] = { // ModAmount
    {47, 0},
    {113, 1},
    {114, 1},
    {18, 0},
};
const ParamItem kParams12_3[] = { // Fade
    {47, 1},
    {113, 0},
    {114, 0},
    {18, 1},
};
const ItemGroup<ParamItem> kParams12[] = {
    {"Linear", kParams12_0},
    {"Padding", kParams12_1},
    {"ModAmount", kParams12_2},
    {"Fade", kParams12_3},
};

// Filter Group (CReplaceDataBase::Module_Begin @ 0011234c)
const Member kMembers13[] = {
    {87, 7}, // FltLP
    {134, 7}, // FltHP
    {51, 7}, // FltNord
    {92, 7}, // FltClassic
    {49, 7}, // FltMulti
    {54, 7}, // FltStatic
    {102, 7}, // FltPhase
    {162, 7}, // FltComb
    {125, 7}, // WahWah
    {45, 7}, // FltVoice
    {108, 7}, // Vocoder
    {103, 7}, // EqPeak
    {32, 7}, // Eq2Band
    {33, 7}, // Eq3band
};
const InputItem kInputs13_0[] = { // Audio In
    {87, 0, 255, 255},
    {134, 0, 255, 255},
    {51, 0, 255, 255},
    {92, 0, 255, 255},
    {49, 0, 255, 255},
    {54, 0, 255, 255},
    {125, 0, 255, 255},
    {45, 0, 255, 255},
    {108, 1, 255, 255},
    {102, 0, 255, 255},
    {162, 0, 255, 255},
    {32, 0, 255, 255},
    {33, 0, 255, 255},
    {103, 0, 255, 255},
};
const InputItem kInputs13_1[] = { // Pitch Mod Fix
    {51, 2, 255, 255},
    {92, 2, 255, 255},
    {49, 2, 255, 255},
    {102, 4, 255, 255},
    {162, 1, 255, 255},
};
const InputItem kInputs13_2[] = { // Pitch Mod
    {87, 1, 1, 255},
    {134, 1, 1, 255},
    {51, 1, 1, 255},
    {92, 1, 1, 255},
    {49, 1, 1, 255},
    {125, 1, 0, 255},
    {45, 2, 7, 255},
    {102, 1, 0, 255},
    {162, 2, 1, 255},
};
const InputItem kInputs13_3[] = { // Feedback Mod
    {102, 3, 8, 255},
    {162, 3, 4, 255},
};
const ItemGroup<InputItem> kInputs13[] = {
    {"Audio In", kInputs13_0},
    {"Pitch Mod Fix", kInputs13_1},
    {"Pitch Mod", kInputs13_2},
    {"Feedback Mod", kInputs13_3},
};
const OutputItem kOutputs13_0[] = { // Audio Out
    {87, 0},
    {134, 0},
    {51, 0},
    {92, 0},
    {49, 0},
    {54, 0},
    {125, 0},
    {45, 0},
    {108, 0},
    {102, 0},
    {162, 0},
    {32, 0},
    {33, 0},
    {103, 0},
};
const ItemGroup<OutputItem> kOutputs13[] = {
    {"Audio Out", kOutputs13_0},
};
const ParamItem kParams13_0[] = { // Cutoff
    {87, 0},
    {134, 0},
    {51, 0},
    {92, 0},
    {49, 0},
    {54, 0},
    {125, 1},
    {45, 6},
    {102, 1},
    {162, 0},
    {33, 2},
    {103, 0},
};
const ParamItem kParams13_1[] = { // Bypass
    {87, 3},
    {134, 3},
    {51, 6},
    {92, 5},
    {49, 6},
    {54, 3},
    {125, 2},
    {45, 9},
    {108, 9},
    {102, 6},
    {162, 7},
    {32, 3},
    {33, 5},
    {103, 3},
};
const ParamItem kParams13_2[] = { // Res
    {51, 4},
    {92, 3},
    {49, 4},
    {45, 8},
    {54, 1},
};
const ParamItem kParams13_3[] = { // KBT
    {87, 2},
    {134, 2},
    {51, 2},
    {92, 2},
    {49, 2},
    {102, 10},
    {162, 2},
};
const ParamItem kParams13_4[] = { // InLvl
    {102, 7},
    {162, 6},
    {33, 4},
    {32, 2},
    {103, 4},
};
const ParamItem kParams13_5[] = { // Feedback
    {102, 3},
    {162, 3},
};
const ParamItem kParams13_6[] = { // FeedbackAmount
    {102, 8},
    {162, 4},
};
const ParamItem kParams13_7[] = { // Variant
    {102, 9},
    {162, 5},
};
const ParamItem kParams13_8[] = { // Lo Gain
    {32, 1},
    {33, 3},
};
const ParamItem kParams13_9[] = { // Lo Freq
    {32, 5},
    {33, 7},
};
const ParamItem kParams13_10[] = { // Hi Freq
    {32, 4},
    {33, 6},
};
const ItemGroup<ParamItem> kParams13[] = {
    {"Cutoff", kParams13_0},
    {"Bypass", kParams13_1},
    {"Res", kParams13_2},
    {"KBT", kParams13_3},
    {"InLvl", kParams13_4},
    {"Feedback", kParams13_5},
    {"FeedbackAmount", kParams13_6},
    {"Variant", kParams13_7},
    {"Lo Gain", kParams13_8},
    {"Lo Freq", kParams13_9},
    {"Hi Freq", kParams13_10},
};

// Effect Group (CReplaceDataBase::Module_Begin @ 001133c0)
const Member kMembers14[] = {
    {94, 7}, // StChorus
    {118, 7}, // Digitizer
    {89, 7}, // Flanger
    {98, 7}, // FreqShift
    {12, 7}, // Reverb
    {150, 7}, // Compress
    {192, 7}, // Phaser
    {167, 7}, // PShift
    {63, 7}, // Scratch
};
const InputItem kInputs14_0[] = { // Inputs
    {94, 0, 255, 255},
    {118, 0, 255, 255},
    {89, 0, 255, 255},
    {98, 0, 255, 255},
    {12, 0, 255, 255},
    {12, 1, 255, 255},
    {150, 0, 255, 255},
    {150, 1, 255, 255},
    {192, 0, 255, 255},
    {167, 0, 255, 255},
    {63, 0, 255, 255},
};
const InputItem kInputs14_1[] = { // Modulation
    {63, 1, 1, 255},
    {167, 1, 2, 255},
    {98, 1, 1, 255},
    {118, 1, 2, 255},
};
const ItemGroup<InputItem> kInputs14[] = {
    {"Inputs", kInputs14_0},
    {"Modulation", kInputs14_1},
};
const OutputItem kOutputs14_0[] = { // Outputs
    {94, 0},
    {94, 1},
    {118, 0},
    {89, 0},
    {98, 0},
    {98, 1},
    {12, 0},
    {12, 1},
    {150, 1},
    {150, 0},
    {192, 0},
    {167, 0},
    {63, 0},
};
const ItemGroup<OutputItem> kOutputs14[] = {
    {"Outputs", kOutputs14_0},
};
const ParamItem kParams14_0[] = { // Bypass
    {94, 2},
    {118, 3},
    {89, 3},
    {12, 3},
    {150, 6},
    {192, 3},
    {167, 4},
    {63, 3},
    {98, 3},
};
const ParamItem kParams14_1[] = { // Rate
    {89, 0},
    {192, 1},
};
const ParamItem kParams14_2[] = { // Depth
    {89, 1},
};
const ItemGroup<ParamItem> kParams14[] = {
    {"Bypass", kParams14_0},
    {"Rate", kParams14_1},
    {"Depth", kParams14_2},
};

// LFO Group (CReplaceDataBase::Module_Begin @ 00113ab5)
const Member kMembers15[] = {
    {26, 7}, // LfoA
    {190, 7}, // LfoB
    {24, 7}, // LfoC
    {25, 7}, // LfoShpA
    {68, 7}, // ClkGen
};
const InputItem kInputs15_0[] = { // Pitch Fixed
    {26, 0, 255, 255},
    {190, 0, 255, 255},
    {25, 0, 255, 255},
    {24, 0, 255, 255},
};
const InputItem kInputs15_1[] = { // Reset
    {190, 2, 255, 255},
    {25, 2, 255, 255},
};
const InputItem kInputs15_2[] = { // Pitch
    {26, 1, 3, 255},
    {190, 1, 1, 255},
    {25, 1, 3, 255},
};
const ItemGroup<InputItem> kInputs15[] = {
    {"Pitch Fixed", kInputs15_0},
    {"Reset", kInputs15_1},
    {"Pitch", kInputs15_2},
};
const OutputItem kOutputs15_0[] = { // Outputs
    {26, 0},
    {190, 0},
    {25, 0},
    {24, 0},
};
const OutputItem kOutputs15_1[] = { // SyncOut
    {190, 1},
    {25, 1},
};
const ItemGroup<OutputItem> kOutputs15[] = {
    {"Outputs", kOutputs15_0},
    {"SyncOut", kOutputs15_1},
};
const ParamItem kParams15_0[] = { // Params Freq
    {26, 0},
    {190, 0},
    {25, 0},
    {24, 0},
};
const ParamItem kParams15_1[] = { // Params Range
    {26, 7},
    {190, 2},
    {25, 1},
    {24, 3},
};
const ParamItem kParams15_2[] = { // Params Mono
    {26, 1},
    {190, 5},
    {25, 9},
    {24, 1},
};
const ParamItem kParams15_3[] = { // Params KBT
    {26, 2},
    {190, 3},
    {25, 2},
};
const ParamItem kParams15_4[] = { // Params Mute
    {26, 5},
    {190, 7},
    {25, 4},
    {24, 4},
};
const ParamItem kParams15_5[] = { // LevelShift
    {26, 6},
    {190, 8},
    {25, 10},
    {24, 2},
};
const ItemGroup<ParamItem> kParams15[] = {
    {"Params Freq", kParams15_0},
    {"Params Range", kParams15_1},
    {"Params Mono", kParams15_2},
    {"Params KBT", kParams15_3},
    {"Params Mute", kParams15_4},
    {"LevelShift", kParams15_5},
};

// RND Group (CReplaceDataBase::Module_Begin @ 0011411a)
const Member kMembers16[] = {
    {200, 7}, // RandomA
    {202, 7}, // RandomB
    {204, 7}, // RndClkA
    {206, 7}, // RndClkB
    {205, 7}, // RndTrig
    {208, 7}, // RndPattern
};
const InputItem kInputs16_0[] = { // Pitch Fixed
    {200, 0, 255, 255},
    {202, 0, 255, 255},
};
const InputItem kInputs16_1[] = { // Pitch
    {202, 1, 3, 255},
};
const InputItem kInputs16_2[] = { // Clk
    {204, 0, 255, 255},
    {205, 0, 255, 255},
    {206, 0, 255, 255},
    {208, 0, 255, 255},
};
const InputItem kInputs16_3[] = { // Reset
    {204, 1, 255, 255},
    {205, 1, 255, 255},
    {206, 1, 255, 255},
    {208, 1, 255, 255},
};
const InputItem kInputs16_4[] = { // SeedInput
    {204, 2, 255, 255},
    {205, 2, 255, 255},
    {206, 2, 255, 255},
    {208, 2, 255, 255},
    {208, 3, 255, 255},
};
const InputItem kInputs16_5[] = { // Step
    {206, 3, 4, 255},
    {208, 4, 4, 255},
};
const ItemGroup<InputItem> kInputs16[] = {
    {"Pitch Fixed", kInputs16_0},
    {"Pitch", kInputs16_1},
    {"Clk", kInputs16_2},
    {"Reset", kInputs16_3},
    {"SeedInput", kInputs16_4},
    {"Step", kInputs16_5},
};
const OutputItem kOutputs16_0[] = { // MainOut
    {200, 0},
    {202, 0},
    {204, 0},
    {205, 0},
    {206, 0},
    {208, 0},
};
const ItemGroup<OutputItem> kOutputs16[] = {
    {"MainOut", kOutputs16_0},
};
const ParamItem kParams16_0[] = { // Smooth
    {200, 5},
    {202, 8},
};
const ParamItem kParams16_1[] = { // Step
    {200, 6},
    {202, 4},
    {204, 0},
    {206, 0},
    {208, 2},
};
const ParamItem kParams16_2[] = { // Prob
    {205, 0},
};
const ParamItem kParams16_3[] = { // LevShift
    {200, 2},
    {202, 6},
    {204, 3},
    {206, 1},
    {208, 5},
};
const ParamItem kParams16_4[] = { // Mono
    {200, 1},
    {202, 1},
    {204, 1},
    {205, 3},
    {206, 3},
};
const ParamItem kParams16_5[] = { // Active
    {200, 4},
    {202, 5},
    {204, 4},
    {205, 2},
    {206, 2},
    {208, 6},
};
const ParamItem kParams16_6[] = { // Rate
    {200, 0},
    {202, 0},
};
const ParamItem kParams16_7[] = { // Range
    {200, 3},
    {202, 7},
};
const ItemGroup<ParamItem> kParams16[] = {
    {"Smooth", kParams16_0},
    {"Step", kParams16_1},
    {"Prob", kParams16_2},
    {"LevShift", kParams16_3},
    {"Mono", kParams16_4},
    {"Active", kParams16_5},
    {"Rate", kParams16_6},
    {"Range", kParams16_7},
};

// Sequencer Group (CReplaceDataBase::Module_Begin @ 00114a10)
const Member kMembers17[] = {
    {144, 7}, // SeqEvent
    {145, 7}, // SeqVal
    {146, 7}, // SeqLev
    {121, 7}, // SeqNote
    {154, 7}, // SeqCtr
};
const InputItem kInputs17_0[] = { // Clock Inputs
    {144, 0, 255, 255},
    {145, 0, 255, 255},
    {146, 0, 255, 255},
    {121, 0, 255, 255},
};
const InputItem kInputs17_1[] = { // Rst Inputs
    {144, 1, 255, 255},
    {145, 1, 255, 255},
    {146, 1, 255, 255},
    {121, 1, 255, 255},
};
const InputItem kInputs17_2[] = { // Loop Inputs
    {144, 2, 255, 255},
    {145, 2, 255, 255},
    {146, 2, 255, 255},
    {121, 2, 255, 255},
};
const InputItem kInputs17_3[] = { // Park Inputs
    {144, 3, 255, 255},
    {145, 3, 255, 255},
    {146, 3, 255, 255},
    {121, 3, 255, 255},
};
const InputItem kInputs17_4[] = { // Chain1 Inputs
    {144, 4, 255, 255},
    {145, 4, 255, 255},
    {146, 4, 255, 255},
    {121, 4, 255, 255},
    {154, 1, 255, 255},
};
const InputItem kInputs17_5[] = { // Chain2 Inputs
    {144, 5, 255, 255},
    {145, 5, 255, 255},
    {146, 5, 255, 255},
    {121, 5, 255, 255},
    {154, 2, 255, 255},
};
const ItemGroup<InputItem> kInputs17[] = {
    {"Clock Inputs", kInputs17_0},
    {"Rst Inputs", kInputs17_1},
    {"Loop Inputs", kInputs17_2},
    {"Park Inputs", kInputs17_3},
    {"Chain1 Inputs", kInputs17_4},
    {"Chain2 Inputs", kInputs17_5},
};
const OutputItem kOutputs17_0[] = { // Link Outputs
    {144, 0},
    {145, 0},
    {146, 0},
    {121, 0},
};
const OutputItem kOutputs17_1[] = { // Chain1 Outputs
    {144, 1},
    {145, 1},
    {146, 1},
    {121, 1},
    {154, 0},
};
const OutputItem kOutputs17_2[] = { // Chain2 Outputs
    {144, 2},
    {145, 2},
    {146, 2},
    {121, 2},
    {154, 1},
};
const ItemGroup<OutputItem> kOutputs17[] = {
    {"Link Outputs", kOutputs17_0},
    {"Chain1 Outputs", kOutputs17_1},
    {"Chain2 Outputs", kOutputs17_2},
};
const ParamItem kParams17_0[] = { // Loop
    {144, 32},
    {145, 32},
    {146, 32},
    {121, 32},
};
const ParamItem kParams17_1[] = { // Length
    {144, 33},
    {145, 33},
    {146, 33},
    {121, 33},
};
const ParamItem kParams17_2[] = { // Polarity
    {145, 34},
    {146, 34},
    {154, 33},
};
const ParamItem kParams17_3[] = { // Value 1
    {144, 0},
    {145, 0},
    {146, 0},
    {121, 0},
    {154, 0},
};
const ParamItem kParams17_4[] = { // Value 2
    {144, 1},
    {145, 1},
    {146, 1},
    {121, 1},
    {154, 1},
};
const ParamItem kParams17_5[] = { // Value 3
    {144, 2},
    {145, 2},
    {146, 2},
    {121, 2},
    {154, 2},
};
const ParamItem kParams17_6[] = { // Value 4
    {144, 3},
    {145, 3},
    {146, 3},
    {121, 3},
    {154, 3},
};
const ParamItem kParams17_7[] = { // Value 5
    {144, 4},
    {145, 4},
    {146, 4},
    {121, 4},
    {154, 4},
};
const ParamItem kParams17_8[] = { // Value 6
    {144, 5},
    {145, 5},
    {146, 5},
    {121, 5},
    {154, 5},
};
const ParamItem kParams17_9[] = { // Value 7
    {144, 6},
    {145, 6},
    {146, 6},
    {121, 6},
    {154, 6},
};
const ParamItem kParams17_10[] = { // Value 8
    {144, 7},
    {145, 7},
    {146, 7},
    {121, 7},
    {154, 7},
};
const ParamItem kParams17_11[] = { // Value 9
    {144, 8},
    {145, 8},
    {146, 8},
    {121, 8},
    {154, 8},
};
const ParamItem kParams17_12[] = { // Value 10
    {144, 9},
    {145, 9},
    {146, 9},
    {121, 9},
    {154, 9},
};
const ParamItem kParams17_13[] = { // Value 11
    {144, 10},
    {145, 10},
    {146, 10},
    {121, 10},
    {154, 10},
};
const ParamItem kParams17_14[] = { // Value 12
    {144, 11},
    {145, 11},
    {146, 11},
    {121, 11},
    {154, 11},
};
const ParamItem kParams17_15[] = { // Value 13
    {144, 12},
    {145, 12},
    {146, 12},
    {121, 12},
    {154, 12},
};
const ParamItem kParams17_16[] = { // Value 14
    {144, 13},
    {145, 13},
    {146, 13},
    {121, 13},
    {154, 13},
};
const ParamItem kParams17_17[] = { // Value 15
    {144, 14},
    {145, 14},
    {146, 14},
    {121, 14},
    {154, 14},
};
const ParamItem kParams17_18[] = { // Value 16
    {144, 15},
    {145, 15},
    {146, 15},
    {121, 15},
    {154, 15},
};
const ParamItem kParams17_19[] = { // Event 1
    {144, 16},
    {145, 16},
    {146, 16},
    {121, 16},
    {154, 16},
};
const ParamItem kParams17_20[] = { // Event 2
    {144, 17},
    {145, 17},
    {146, 17},
    {121, 17},
    {154, 17},
};
const ParamItem kParams17_21[] = { // Event 3
    {144, 18},
    {145, 18},
    {146, 18},
    {121, 18},
    {154, 18},
};
const ParamItem kParams17_22[] = { // Event 4
    {144, 19},
    {145, 19},
    {146, 19},
    {121, 19},
    {154, 19},
};
const ParamItem kParams17_23[] = { // Event 5
    {144, 20},
    {145, 20},
    {146, 20},
    {121, 20},
    {154, 20},
};
const ParamItem kParams17_24[] = { // Event 6
    {144, 21},
    {145, 21},
    {146, 21},
    {121, 21},
    {154, 21},
};
const ParamItem kParams17_25[] = { // Event 7
    {144, 22},
    {145, 22},
    {146, 22},
    {121, 22},
    {154, 22},
};
const ParamItem kParams17_26[] = { // Event 8
    {144, 23},
    {145, 23},
    {146, 23},
    {121, 23},
    {154, 23},
};
const ParamItem kParams17_27[] = { // Event 9
    {144, 24},
    {145, 24},
    {146, 24},
    {121, 24},
    {154, 24},
};
const ParamItem kParams17_28[] = { // Event 10
    {144, 25},
    {145, 25},
    {146, 25},
    {121, 25},
    {154, 25},
};
const ParamItem kParams17_29[] = { // Event 11
    {144, 26},
    {145, 26},
    {146, 26},
    {121, 26},
    {154, 26},
};
const ParamItem kParams17_30[] = { // Event 12
    {144, 27},
    {145, 27},
    {146, 27},
    {121, 27},
    {154, 27},
};
const ParamItem kParams17_31[] = { // Event 13
    {144, 28},
    {145, 28},
    {146, 28},
    {121, 28},
    {154, 28},
};
const ParamItem kParams17_32[] = { // Event 14
    {144, 29},
    {145, 29},
    {146, 29},
    {121, 29},
    {154, 29},
};
const ParamItem kParams17_33[] = { // Event 15
    {144, 30},
    {145, 30},
    {146, 30},
    {121, 30},
    {154, 30},
};
const ParamItem kParams17_34[] = { // Event 16
    {144, 31},
    {145, 31},
    {146, 31},
    {121, 31},
    {154, 31},
};
const ParamItem kParams17_35[] = { // Gate
    {144, 35},
    {145, 35},
    {146, 35},
    {121, 34},
    {154, 32},
};
const ItemGroup<ParamItem> kParams17[] = {
    {"Loop", kParams17_0},
    {"Length", kParams17_1},
    {"Polarity", kParams17_2},
    {"Value 1", kParams17_3},
    {"Value 2", kParams17_4},
    {"Value 3", kParams17_5},
    {"Value 4", kParams17_6},
    {"Value 5", kParams17_7},
    {"Value 6", kParams17_8},
    {"Value 7", kParams17_9},
    {"Value 8", kParams17_10},
    {"Value 9", kParams17_11},
    {"Value 10", kParams17_12},
    {"Value 11", kParams17_13},
    {"Value 12", kParams17_14},
    {"Value 13", kParams17_15},
    {"Value 14", kParams17_16},
    {"Value 15", kParams17_17},
    {"Value 16", kParams17_18},
    {"Event 1", kParams17_19},
    {"Event 2", kParams17_20},
    {"Event 3", kParams17_21},
    {"Event 4", kParams17_22},
    {"Event 5", kParams17_23},
    {"Event 6", kParams17_24},
    {"Event 7", kParams17_25},
    {"Event 8", kParams17_26},
    {"Event 9", kParams17_27},
    {"Event 10", kParams17_28},
    {"Event 11", kParams17_29},
    {"Event 12", kParams17_30},
    {"Event 13", kParams17_31},
    {"Event 14", kParams17_32},
    {"Event 15", kParams17_33},
    {"Event 16", kParams17_34},
    {"Gate", kParams17_35},
};

// Logic Group (CReplaceDataBase::Module_Begin @ 001169c3)
const Member kMembers18[] = {
    {64, 7}, // Gate
    {5, 7}, // Invert
    {91, 7}, // FlipFlop
    {69, 7}, // ClkDiv
    {38, 7}, // Pulse
    {42, 7}, // Delay
    {86, 7}, // 8Counter
    {130, 7}, // BinCounter
    {131, 7}, // ADConv
    {132, 7}, // DAConv
};
const InputItem kInputs18_0[] = { // Inputs Clock
    {91, 0, 255, 255},
    {69, 0, 255, 255},
    {86, 0, 255, 255},
    {130, 0, 255, 255},
};
const InputItem kInputs18_1[] = { // Inputs Reset
    {91, 2, 255, 255},
    {69, 1, 255, 255},
    {86, 1, 255, 255},
    {130, 1, 255, 255},
};
const InputItem kInputs18_2[] = { // Inputs Mod
    {38, 1, 1, 255},
    {42, 1, 1, 255},
};
const InputItem kInputs18_3[] = { // Inputs
    {64, 1, 255, 255},
    {64, 0, 255, 255},
    {64, 3, 255, 255},
    {64, 2, 255, 255},
    {5, 1, 255, 255},
    {5, 0, 255, 255},
    {91, 1, 255, 255},
    {38, 0, 255, 255},
    {42, 0, 255, 255},
    {132, 0, 255, 255},
    {132, 1, 255, 255},
    {132, 2, 255, 255},
    {132, 3, 255, 255},
    {132, 4, 255, 255},
    {132, 5, 255, 255},
    {132, 6, 255, 255},
    {132, 7, 255, 255},
};
const ItemGroup<InputItem> kInputs18[] = {
    {"Inputs Clock", kInputs18_0},
    {"Inputs Reset", kInputs18_1},
    {"Inputs Mod", kInputs18_2},
    {"Inputs", kInputs18_3},
};
const OutputItem kOutputs18_0[] = { // OutPuts
    {64, 0},
    {64, 1},
    {5, 0},
    {5, 1},
    {91, 1},
    {91, 0},
    {69, 0},
    {38, 0},
    {42, 0},
    {86, 0},
    {86, 1},
    {86, 2},
    {86, 3},
    {86, 4},
    {86, 5},
    {86, 6},
    {86, 7},
    {130, 0},
    {130, 1},
    {130, 2},
    {130, 3},
    {130, 4},
    {130, 5},
    {130, 6},
    {130, 7},
    {131, 0},
    {131, 1},
    {131, 2},
    {131, 3},
    {131, 4},
    {131, 5},
    {131, 6},
    {131, 7},
    {132, 0},
};
const ItemGroup<OutputItem> kOutputs18[] = {
    {"OutPuts", kOutputs18_0},
};
const ParamItem kParams18_0[] = { // Params Time
    {38, 0},
    {42, 0},
    {69, 0},
};
const ParamItem kParams18_1[] = { // Params Range
    {38, 2},
    {42, 2},
};
const ItemGroup<ParamItem> kParams18[] = {
    {"Params Time", kParams18_0},
    {"Params Range", kParams18_1},
};

const Group kGroups[] = {
    {"Shaper Group", kMembers0, kInputs0, kOutputs0, kParams0},
    {"Level Group", kMembers1, kInputs1, kOutputs1, kParams1},
    {"MIDI Group Send", kMembers2, kInputs2, kOutputs2, kParams2},
    {"MIDI Group Recv", kMembers3, {}, kOutputs3, kParams3},
    {"Note Group", kMembers4, kInputs4, kOutputs4, kParams4},
    {"Osc Group", kMembers5, kInputs5, kOutputs5, kParams5},
    {"Keyboard Group", kMembers6, {}, kOutputs6, {}},
    {"Input Group", kMembers7, {}, kOutputs7, kParams7},
    {"Output Group", kMembers8, kInputs8, {}, kParams8},
    {"Env Group", kMembers9, kInputs9, kOutputs9, kParams9},
    {"Delay Group", kMembers10, kInputs10, kOutputs10, kParams10},
    {"Switch Group", kMembers11, kInputs11, kOutputs11, kParams11},
    {"Mix Group", kMembers12, kInputs12, kOutputs12, kParams12},
    {"Filter Group", kMembers13, kInputs13, kOutputs13, kParams13},
    {"Effect Group", kMembers14, kInputs14, kOutputs14, kParams14},
    {"LFO Group", kMembers15, kInputs15, kOutputs15, kParams15},
    {"RND Group", kMembers16, kInputs16, kOutputs16, kParams16},
    {"Sequencer Group", kMembers17, kInputs17, kOutputs17, kParams17},
    {"Logic Group", kMembers18, kInputs18, kOutputs18, kParams18},
};

} // namespace

std::span<const Group> groups()
{
    return kGroups;
}

} // namespace g2::replace
