#!/usr/bin/env python3
"""Generates core/src/mutate_classes.inc: the editor's "param class" byte
(param spec +0x12, `paramClass` in data/modules.json) of every parameter of
every module type. The Patch Mutator (core/src/mutate.cpp) decides from it
which parameters it may change and with which distribution
(re/notes/randomize-mutate.md).

    gen_param_classes.py [--check]

--check exits 1 if the committed file is out of date.
"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SRC = os.path.join(ROOT, "data", "modules.json")
OUT = os.path.join(ROOT, "core", "src", "mutate_classes.inc")


def generate():
    with open(SRC, encoding="utf-8") as f:
        modules = json.load(f)["modules"]
    rows = {}
    for m in modules:
        t = m.get("typeId")
        if t is None or not m["params"]:
            continue
        classes = [p.get("paramClass") for p in m["params"]]
        if any(c is None for c in classes):
            continue  # modules the editor does not have (Verhue-only)
        rows[t] = (m["shortName"], classes)
    out = [
        "// Generated by tools/mutate/gen_param_classes.py from data/modules.json. Do not edit.",
        "// Param class (param spec byte 0x12) per module type and parameter.",
        "",
    ]
    for t in sorted(rows):
        name, classes = rows[t]
        out.append("constexpr std::uint8_t kClasses%d[] = {%s}; // %s" % (t, ", ".join(str(c) for c in classes), name))
    out.append("")
    out.append("struct ClassRow {")
    out.append("    std::uint8_t type;")
    out.append("    std::uint8_t count;")
    out.append("    const std::uint8_t* classes;")
    out.append("};")
    out.append("constexpr ClassRow kClassRows[] = {")
    for t in sorted(rows):
        out.append("    {%d, %d, kClasses%d}," % (t, len(rows[t][1]), t))
    out.append("};")
    return "\n".join(out) + "\n"


def main():
    text = generate()
    if "--check" in sys.argv:
        with open(OUT, encoding="utf-8") as f:
            if f.read() != text:
                print("%s is out of date; run %s" % (OUT, sys.argv[0]))
                sys.exit(1)
        return
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(text)


if __name__ == "__main__":
    main()
