#!/usr/bin/env python3
"""Generates core/src/module_db_data.cpp from data/modules.json,
data/param_text.json and the panel layouts (assets/clavia/panels.json, for
the label controls), so the editor carries its module database compiled in.

    gen_cpp.py [--check]

--check exits 1 if the committed file is out of date (used by the tests).
"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT = os.path.join(ROOT, "core", "src", "module_db_data.cpp")

KIND = {"module": "Module", "patchSettings": "PatchSettings", "name": "NameBar"}
SIGNAL = {"audio": "Audio", "control": "Control", "logic": "Logic"}
COLOR = {"red": "Red", "blue": "Blue", "yellow": "Yellow", "blue_red": "BlueRed",
         "yellow_orange": "YellowOrange"}
BANDWIDTH = {"static": "Static", "dynamic": "Dynamic"}


def cstr(s):
    if s is None:
        return "nullptr"
    out = '"'
    for ch in s.encode("utf-8"):
        c = chr(ch)
        if c in '"\\':
            out += "\\" + c
        elif 0x20 <= ch < 0x7F:
            out += c
        else:
            out += '\\%03o' % ch
    return out + '"'


# Display functions of the patch-settings pseudo modules, registered with
# hard-coded ids by CBModuleToolbar::CBModuleToolbar @0x8e4f2 (see
# re/notes/param-display.md section 2.1). Morph dials (params 0..7) use Default.
SETTINGS_TEXT = {
    6: {8 + i: 221 + i for i in range(8)},         # Morph: group sources
    95: {0: 118, 1: 7},                            # Gain: master volume, mute
    135: {0: 116, 1: 115},                         # Glide: type, time
    137: {0: 117, 1: 162},                         # Bend: on/off, range
    138: {0: 120, 1: 119, 2: 171},                 # Vibrato: mode, amount, rate
    136: {0: 3, 1: 112, 2: 113, 3: 111},           # Arpeggiator: on, rate, mode, range
    153: {0: 121, 1: 3},                           # Misc: octave shift, sustain
}


def dep_code(dep):
    """'param3' -> 3, 'mode0' -> 0x80 | 0 (same encoding as the module-info records)."""
    if dep.startswith("param"):
        return int(dep[5:])
    if dep.startswith("mode"):
        return 0x80 | int(dep[4:])
    raise ValueError("unknown dependency " + dep)


def label_controls(mdb):
    """Per module type, the panel's label controls in panel order: the PANL
    `TextEdit` (CPnlLabelButton) and `ButtonRadioEdit` (CPnlLabelRadioButton)
    elements, whose captions the user can rename (CanChangeName) and which
    write one custom-data record each (CPanel::GetCustomData)."""
    with open(os.path.join(ROOT, "assets", "clavia", "panels.json"), encoding="utf-8") as f:
        panels = json.load(f)
    type_of = {m.get("panelResId"): m["typeId"] for m in mdb["modules"] if m.get("panelResId")}
    out = {}

    def walk(node, found):
        if node.get("type") in ("TextEdit", "ButtonRadioEdit"):
            found.append(node)
        for child in node.get("children", []):
            walk(child, found)

    for panel in panels:
        found = []
        walk(panel, found)
        t = type_of.get(panel.get("resId"))
        if t is None or not found:
            continue
        labels = []
        for e in found:
            texts = [x for x in (e.get("Text") or "").split(",") if x != ""]
            if e["type"] == "TextEdit":
                buttons = 1
            else:
                buttons = int(e.get("ButtonColumns", 1)) * int(e.get("ButtonRows", 1))
            labels.append((int(e["CodeRef"]), buttons, ",".join(texts)))
        out[t] = labels
    return out


def generate():
    with open(os.path.join(ROOT, "data", "modules.json"), encoding="utf-8") as f:
        mdb = json.load(f)
    with open(os.path.join(ROOT, "data", "param_text.json"), encoding="utf-8") as f:
        ptx = json.load(f)
    bindings = {m["type_id"]: {p["index"]: p for p in m["params"]} for m in ptx["modules"]}
    help_path = os.path.join(ROOT, "data", "module_help.json")
    descriptions = {}
    if os.path.exists(help_path):
        with open(help_path, encoding="utf-8") as f:
            descriptions = json.load(f)

    lines = [
        "// Generated by tools/moduledb/gen_cpp.py from data/modules.json and",
        "// data/param_text.json. Do not edit by hand.",
        '#include "g2/module_db.hpp"',
        "",
        "#include <iterator>",
        "",
        "namespace g2::db {",
        "namespace {",
        "",
    ]
    modules = sorted(mdb["modules"], key=lambda m: m["typeId"])
    labels = label_controls(mdb)
    for m in modules:
        t = m["typeId"]
        if t in labels:
            lines.append(f"const LabelDef kLabels{t}[] = {{")
            for param, buttons, texts in labels[t]:
                lines.append(f"    {{{param}, {buttons}, {cstr(texts)}}},")
            lines.append("};")
        for kind in ("inputs", "outputs"):
            conns = m.get(kind) or []
            if not conns:
                continue
            lines.append(f"const ConnectorDef k{kind.capitalize()}{t}[] = {{")
            for c in conns:
                lines.append(f"    {{{cstr(c['name'])}, SignalType::{SIGNAL[c['type']]}, "
                             f"ConnColor::{COLOR[c['color']]}, Bandwidth::{BANDWIDTH[c['bandwidth']]}}},")
            lines.append("};")
        params = m.get("params") or []
        if params:
            lines.append(f"const ParamDef kParams{t}[] = {{")
            for p in params:
                b = bindings.get(t, {}).get(p["index"])
                if b is not None:
                    func, deps = b["func_id"], [dep_code(d) for d in b["deps"]]
                elif p["index"] in SETTINGS_TEXT.get(t, {}):
                    func, deps = SETTINGS_TEXT[t][p["index"]], []
                else:
                    func, deps = p.get("infoFunc") or 0, []
                deps += [0xFF] * (2 - len(deps))
                lines.append(f"    {{{cstr(p['name'])}, {p['min']}, {p['max']}, {p['default']}, "
                             f"{'true' if p.get('morphable') else 'false'}, {func}, "
                             f"{{{deps[0]}, {deps[1]}}}, {cstr(p.get('rangeType'))}, "
                             f"{'true' if p.get('momentary') else 'false'}, "
                             f"{'false' if p.get('midiAssignable') is False else 'true'}}},")
            lines.append("};")
        modes = m.get("modes") or []
        if modes:
            lines.append(f"const ModeDef kModes{t}[] = {{")
            for p in modes:
                lines.append(f"    {{{cstr(p['name'])}, {p['min']}, {p['max']}, {p['default']}, "
                             f"{p.get('infoFunc') or 0}, {cstr(p.get('rangeType'))}}},")
            lines.append("};")

    lines += ["", "} // namespace", "",
              "extern const ModuleDef kModules[];",
              "extern const CategoryDef kCategories[];",
              "extern const std::size_t kModuleCount;",
              "extern const std::size_t kCategoryCount;",
              "", "const ModuleDef kModules[] = {"]
    for m in modules:
        t = m["typeId"]
        fl = m.get("flags") or {}

        def span(prefix, key):
            return f"k{prefix}{t}" if m.get(key) else "{}"
        lines.append(
            f"    {{{t}, ModuleKind::{KIND[m['kind']]}, {cstr(m['shortName'])}, {cstr(m.get('longName'))}, "
            f"{m.get('height') or 0}, {m.get('categoryIndex', -1) if m.get('categoryIndex') is not None else -1}, "
            f"{'true' if fl.get('selectable') else 'false'}, {'true' if fl.get('defaultLocked') else 'false'}, "
            f"{m.get('panelResId') or 0}, {m.get('faceResId') or 0}, "
            f"{span('Inputs', 'inputs')}, {span('Outputs', 'outputs')}, "
            f"{span('Params', 'params')}, {span('Modes', 'modes')}, {cstr(descriptions.get(m['shortName']))}, "
            f"{m['toolbarSlot'] if m.get('toolbarSlot') is not None else 255}, "
            f"{('kLabels' + str(t)) if t in labels else '{}'}}},")
    lines += ["};", "", "const CategoryDef kCategories[] = {"]
    for c in mdb["categories"]:
        r, g, b = c["color"]
        lines.append(f"    {{{cstr(c['name'])}, {r}, {g}, {b}}},")
    lines += ["};", "",
              "const std::size_t kModuleCount = std::size(kModules);",
              "const std::size_t kCategoryCount = std::size(kCategories);",
              "", "} // namespace g2::db", ""]
    return "\n".join(lines)


def main(argv):
    text = generate()
    if "--check" in argv:
        # Compare as UTF-8 text, ignoring line endings (git may check out CRLF).
        with open(OUT, encoding="utf-8") as f:
            if f.read().replace("\r\n", "\n") != text:
                print("core/src/module_db_data.cpp is out of date; run tools/moduledb/gen_cpp.py")
                return 1
        print("module_db_data.cpp is up to date")
        return 0
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print("wrote " + os.path.relpath(OUT, ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
