#!/usr/bin/env python3
"""Generates data/replace.json and core/src/replace_data.cpp (the module Replace
database of the original editor) from tools/moduledb/replace_facts.json and
data/modules.json. See re/notes/module-replace.md.

    gen_replace.py [--check]

--check exits 1 if a committed output is out of date.
"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
FACTS = os.path.join(ROOT, "tools", "moduledb", "replace_facts.json")
OUT_JSON = os.path.join(ROOT, "data", "replace.json")
OUT_CPP = os.path.join(ROOT, "core", "src", "replace_data.cpp")

CONTEXT_BITS = {"fx": 1, "va": 2, "patchSettings": 4}   # NSFile_V7::EContext bit = location
NONE = 0xFF


def cstr(s):
    out = '"'
    for ch in s.encode("utf-8"):
        c = chr(ch)
        if c in '"\\':
            out += "\\" + c
        elif 0x20 <= ch < 0x7F:
            out += c
        else:
            out += '\\%03o' % ch
    return out + '"'


def load():
    with open(FACTS) as f:
        facts = json.load(f)
    with open(os.path.join(ROOT, "data", "modules.json")) as f:
        mods = {m["typeId"]: m for m in json.load(f)["modules"]}
    return facts, mods


def check_facts(facts, mods):
    """The facts must agree with the module database (types, connector and param indices)."""
    for g in facts["groups"]:
        types = set(g["types"])
        for sub in g["inputs"]:
            for t, c, a, o in sub["items"]:
                m = mods[t]
                assert t in types and c < len(m["inputs"]), (g["name"], sub["name"], t, c)
                for p in (a, o):
                    assert p == NONE or p < len(m["params"]), (g["name"], sub["name"], t, p)
        for sub in g["outputs"]:
            for t, c in sub["items"]:
                assert t in types and c < len(mods[t]["outputs"]), (g["name"], sub["name"], t, c)
        for sub in g["params"]:
            for t, p in sub["items"]:
                assert t in types and p < len(mods[t]["params"]), (g["name"], sub["name"], t, p)


def contexts(m):
    bits = 0
    for c in (m.get("flags") or {}).get("contexts", []):
        bits |= CONTEXT_BITS[c]
    return bits


def gen_json(facts, mods):
    def pname(t, p):
        return None if p == NONE else mods[t]["params"][p]["name"]

    groups = []
    for g in facts["groups"]:
        groups.append({
            "name": g["name"],
            "ghidra": g["addr"],
            "members": [{"type": t, "shortName": mods[t]["shortName"], "label": mods[t]["longName"],
                         "contexts": (mods[t].get("flags") or {}).get("contexts", [])}
                        for t in g["types"]],
            "inputs": [{"name": s["name"], "items": [
                {"type": t, "module": mods[t]["shortName"], "conn": c, "connName": mods[t]["inputs"][c]["name"],
                 "amountParam": None if a == NONE else a, "amountName": pname(t, a),
                 "onParam": None if o == NONE else o, "onName": pname(t, o)}
                for t, c, a, o in s["items"]]} for s in g["inputs"]],
            "outputs": [{"name": s["name"], "items": [
                {"type": t, "module": mods[t]["shortName"], "conn": c, "connName": mods[t]["outputs"][c]["name"]}
                for t, c in s["items"]]} for s in g["outputs"]],
            "params": [{"name": s["name"], "items": [
                {"type": t, "module": mods[t]["shortName"], "param": p, "paramName": mods[t]["params"][p]["name"]}
                for t, p in s["items"]]} for s in g["params"]],
        })
    doc = {
        "comment": "Module Replace groups and correspondence tables of the G2 editor v1.62, from "
                   "CReplaceDataBase::AddData @ 0010ae74. Generated by tools/moduledb/gen_replace.py "
                   "from tools/moduledb/replace_facts.json and data/modules.json; see "
                   "re/notes/module-replace.md for how the editor uses them.",
        "groups": groups,
    }
    return json.dumps(doc, indent=1, ensure_ascii=False) + "\n"


def gen_cpp(facts, mods):
    L = [
        "// Generated by tools/moduledb/gen_replace.py from tools/moduledb/replace_facts.json",
        "// and data/modules.json. Do not edit by hand.",
        '#include "g2/replace.hpp"',
        "",
        "#include <iterator>",
        "",
        "namespace g2::replace {",
        "namespace {",
        "",
    ]
    for gi, g in enumerate(facts["groups"]):
        L.append(f"// {g['name']} (CReplaceDataBase::Module_Begin @ {g['addr']})")
        L.append(f"const Member kMembers{gi}[] = {{")
        for t in g["types"]:
            L.append(f"    {{{t}, {contexts(mods[t])}}}, // {mods[t]['shortName']}")
        L.append("};")
        for kind, cls in (("inputs", "InputItem"), ("outputs", "OutputItem"), ("params", "ParamItem")):
            for si, s in enumerate(g[kind]):
                L.append(f"const {cls} k{kind.capitalize()}{gi}_{si}[] = {{ // {s['name']}")
                for it in s["items"]:
                    L.append("    {" + ", ".join(str(v) for v in it) + "},")
                L.append("};")
            if g[kind]:
                L.append(f"const ItemGroup<{cls}> k{kind.capitalize()}{gi}[] = {{")
                for si, s in enumerate(g[kind]):
                    L.append(f"    {{{cstr(s['name'])}, k{kind.capitalize()}{gi}_{si}}},")
                L.append("};")
        L.append("")
    L += ["const Group kGroups[] = {"]
    for gi, g in enumerate(facts["groups"]):
        spans = ", ".join(f"k{k.capitalize()}{gi}" if g[k] else "{}" for k in ("inputs", "outputs", "params"))
        L.append(f"    {{{cstr(g['name'])}, kMembers{gi}, {spans}}},")
    L += ["};", "", "} // namespace", "",
          "std::span<const Group> groups()", "{", "    return kGroups;", "}", "",
          "} // namespace g2::replace", ""]
    return "\n".join(L)


def main(argv):
    facts, mods = load()
    check_facts(facts, mods)
    outputs = {OUT_JSON: gen_json(facts, mods), OUT_CPP: gen_cpp(facts, mods)}
    if "--check" in argv:
        stale = [p for p, text in outputs.items()
                 if not os.path.exists(p) or open(p, encoding="utf-8").read() != text]
        for p in stale:
            print(f"{os.path.relpath(p, ROOT)} is out of date; run tools/moduledb/gen_replace.py", file=sys.stderr)
        return 1 if stale else 0
    for p, text in outputs.items():
        with open(p, "w", encoding="utf-8") as f:
            f.write(text)
        print(f"wrote {os.path.relpath(p, ROOT)}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
