#!/usr/bin/env python3
"""Turn the USB-protocol golden vectors (tests/protocol/*.json) into a C++ table
(tests/protocol/vectors.inc) for the Catch2 tests, which have no JSON parser.

  python3 -I tests/protocol/gen_cpp.py          rewrite vectors.inc
  python3 -I tests/protocol/gen_cpp.py --check  exit 1 if vectors.inc is stale
"""

import glob
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "vectors.inc")


def literal(s):
    """A C++ string literal; non-ASCII bytes as octal escapes (UTF-8)."""
    if s is None:
        return "nullptr"
    out = []
    for b in s.encode("utf-8"):
        c = chr(b)
        if c in '"\\':
            out.append("\\" + c)
        elif 32 <= b < 127 and c != "?":  # no trigraphs
            out.append(c)
        else:
            out.append("\\%03o" % b)
    return '"' + "".join(out) + '"'


def generate():
    lines = [
        "// Generated by tests/protocol/gen_cpp.py from tests/protocol/*.json. Do not edit.",
        "// Fields: scenario, step index, direction, endpoint, hex, prefix_hex, valid, annotation.",
        "",
        "inline constexpr ProtoVector kProtoVectors[] = {",
    ]
    crcs = []
    for path in sorted(glob.glob(os.path.join(HERE, "*.json"))):
        with open(path, encoding="utf-8") as f:
            data = json.load(f)
        scenario = data["scenario"]
        for check in data.get("crc_checks", []):
            if "ascii" in check:
                crcs.append("    {%s, true, 0x%s}," % (literal(check["ascii"]), check["crc"]))
            else:
                crcs.append("    {%s, false, 0x%s}," % (literal(check["hex"]), check["crc"]))
        for i, s in enumerate(data["steps"]):
            if s["dir"] not in ("host->device", "device->host"):
                continue
            lines.append("    {%s, %d, %s, %s, %s, %s, %s, %s}," % (
                literal(scenario), i, literal(s["dir"]), literal(s["endpoint"]), literal(s.get("hex")),
                literal(s.get("prefix_hex")), "false" if s.get("valid") is False else "true",
                literal(s.get("annotation", ""))))
    lines.append("};")
    lines.append("")
    lines.append("// CRC-16/XMODEM check values: data (ASCII, or hex bytes), expected CRC.")
    lines.append("inline constexpr CrcVector kCrcVectors[] = {")
    lines += crcs
    lines.append("};")
    return "\n".join(lines) + "\n"


def main(argv):
    text = generate()
    if "--check" in argv:
        with open(OUT, encoding="utf-8") as f:
            if f.read() != text:
                print("tests/protocol/vectors.inc is stale: run python3 -I tests/protocol/gen_cpp.py")
                return 1
        return 0
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print("wrote", os.path.relpath(OUT))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
