#!/usr/bin/env python3
"""Generates core/src/patch_load_data.cpp (the per-module DSP resource figures
used by g2::patchload) from the `resources` records of data/modules.json.

    gen_table.py [--check]

--check exits 1 if the committed file is out of date.

Each record is the module type's `_k<Name>ModuleSize` table (SModuleResourceSpec,
0x20 bytes) as the original editor links it: s16[0] A cycles, s16[1] B cycles,
s16[2] low byte ZP memory / high byte unused, s16[3] unused, s16[4..6] X/Y/P memory
of the A code, s16[7..9] X/Y/P memory of the B code, s32[0] dynamic RAM, s32[1] Q
memory, s32[2] R memory. See re/notes/patch-load.md.
"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT = os.path.join(ROOT, "core", "src", "patch_load_data.cpp")

# The Name bar (type 126) is built by CBModuleName, whose constructor (000bb4e2)
# points the builder at _kNameModuleSize; data/modules.json has no record for it.
# Its contents (all zero but 71 words of dynamic RAM) are read from the binary by
# tools/patchload/emulate.py's golden runs.
EXTRA = {126: {"symbol": "_kNameModuleSize", "s16": [0] * 10, "s32": [71, 0, 0]}}


def generate():
    mods = json.load(open(os.path.join(ROOT, "data", "modules.json"), encoding="utf-8"))["modules"]
    mods = mods if isinstance(mods, list) else list(mods.values())
    rows = {m["typeId"]: (m["shortName"], m["resources"]) for m in mods if m.get("resources")}
    for t, r in EXTRA.items():
        rows.setdefault(t, ("Name", r))
    out = [
        "// Generated by tools/patchload/gen_table.py from data/modules.json.",
        "// Do not edit by hand.",
        '#include "g2/patch_load.hpp"',
        "",
        "#include <array>",
        "",
        "namespace g2::patchload {",
        "namespace {",
        "",
        "struct Row {",
        "    std::uint8_t type;",
        "    ResourceSpec spec;",
        "};",
        "",
        "// {cyclesA, cyclesB, zpMem, unused5, xMemA, yMemA, pMemA, xMemB, yMemB, pMemB, dynRam, qMem, rMem}",
        "constexpr Row kRows[] = {",
    ]
    for t in sorted(rows):
        name, r = rows[t]
        s, l = r["s16"], r["s32"]
        u = [v & 0xFFFF for v in s]
        vals = [u[0], u[1], u[2] & 0xFF, u[2] >> 8, u[4], u[5], u[6], u[7], u[8], u[9],
                l[0] & 0xFFFFFFFF, l[1] & 0xFFFFFFFF, l[2] & 0xFFFFFFFF]
        # u[3] (bytes +6/+7) is never read by the editor (only Automate sets it).
        out.append("    {%d, {%s}}, // %s %s" % (t, ", ".join(str(v) for v in vals), name, r["symbol"]))
    out += [
        "};",
        "",
        "constexpr std::array<const ResourceSpec*, 256> makeIndex()",
        "{",
        "    std::array<const ResourceSpec*, 256> index{};",
        "    for (const Row& r : kRows)",
        "        index[r.type] = &r.spec;",
        "    return index;",
        "}",
        "",
        "constexpr std::array<const ResourceSpec*, 256> kIndex = makeIndex();",
        "",
        "} // namespace",
        "",
        "const ResourceSpec* moduleSpec(std::uint8_t type)",
        "{",
        "    return kIndex[type];",
        "}",
        "",
        "} // namespace g2::patchload",
        "",
    ]
    return "\n".join(out)


def main():
    text = generate()
    if "--check" in sys.argv[1:]:
        try:
            current = open(OUT, encoding="utf-8").read()
        except FileNotFoundError:
            current = None
        if current != text:
            print("%s is out of date; run tools/patchload/gen_table.py" % OUT, file=sys.stderr)
            sys.exit(1)
        return
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(text)


if __name__ == "__main__":
    main()
